### ISSUE TITLE
Image size after crop

### ISSUE THREAD

**Issue by kondasoft** [hnvn/flutter_image_cropper#1]
Thanks for the plugin. It works fine on Android, still haven't tested on iOS

My problem is the image size is much bigger after cropping.

For example i'm uploading an jpeg image with 77kb, but after cropping it goest to 300 kb. 

Is any way to handle image compression with this plugin. or i have to find other ways to handle this.

**Comment by hnvn** [comment]
I will check it.

**Comment by kondasoft** [comment]
great. it seems that image size is ok now
