### ISSUE TITLE
CropAspectRatioPreset ignored on iOS

### ISSUE THREAD

**Issue by saidbeebay** [hnvn/flutter_image_cropper#102]
I want to force the crop to be set to a square.
In my code I did : 

`aspectRatioPresets: [
            CropAspectRatioPreset.square
]
androidUiSettings: AndroidUiSettings(
            toolbarTitle: Translations.of(context).text("cropper") ?? '',
            toolbarColor: Color(this.remoteConfig.getInt('appPrimaryColor')),
            toolbarWidgetColor: Colors.white,
            initAspectRatio: CropAspectRatioPreset.original,
            lockAspectRatio: true),
iosUiSettings: IOSUiSettings(
            aspectRatioLockEnabled: true,
            aspectRatioPickerButtonHidden: true));`

It works on Android, but in iOS, the crop fits the image size.

Is it a bug or am I missing something ?

**Comment by hnvn** [comment]
Document said:
>aspectRatio: controls the aspect ratio of crop bounds. If this values is set, the cropper is locked and user can't change the aspect ratio of crop bounds.

**Comment by saidbeebay** [comment]
May I understand why this issue was closed? 
Can you then give a solution how to lock the crop on iOS to a square from the beginning, even if the chosen image is rectangular ?
Thanks

**Comment by andersonmendesdev** [comment]
I have the same problem on ios, it does not start in square format, aspectRatioPresets is being ignored I need to start with square format, because I want to prevent the user from cutting to another size.

**Comment by hbolin** [comment]
> May I understand why this issue was closed?
> Can you then give a solution how to lock the crop on iOS to a square from the beginning, even if the chosen image is rectangular ?
> Thanks

 aspectRatio: CropAspectRatio(ratioX: 1,ratioY: 1)
