### ISSUE TITLE
Flutter aar build issue

### ISSUE THREAD

**Issue by vlada3003** [hnvn/flutter_image_cropper#106]
We have a flutter library that we use as an aar in our Android native apps. So, to do that
we need to run flutter build aar which won't work. The problem is the outdated Gradle version
in flutter_image_cropper. I have updated the Gradle version and android Gradle plugin to the latest.
[This is the link to the pull request](https://github.com/hnvn/flutter_image_cropper/pull/105)

**Comment by hnvn** [comment]
fixed
