### ISSUE TITLE
How can I set a maximum on zoom and minimum width and height 

### ISSUE THREAD

**Issue by cardila021** [hnvn/flutter_image_cropper#107]
Hi Guys...

Thanks for this amazing flutter plugin... It works very good. However i just wonder if can I set a minimum width and heigth so the User cannot zoom the imagen too much and cropped because in that case I getting as result a picture with too low quality. I just want the user to crop the picture with an aspect ratio as Square.. and lock the user to zoom lower than the minimun width and height so i make sure I get a good quality as result.

Thanks so much.

**Comment by hnvn** [comment]
There's no counterpart feature on both of two native library, so this plugin cannot support it. You may as well handle the image size condition checking on your own codes with the cropped image.
