### ISSUE TITLE
tap bug in ios

### ISSUE THREAD

**Issue by chavesgu** [hnvn/flutter_image_cropper#116]
when I tap the control button at the bottom,if there is a `bottomNavigationBar` wiget behind crop page, the `bottomNavigationBar` will response my tap

**Comment by MiaYi** [comment]
In my case, there is a `TextField` behind crop page, a tap will trigger keyboard present and no way to dismiss it but shut down the app.

**Comment by MiaYi** [comment]
I find out it is a flutter issue about present `UIViewController` on `FlutterViewController`.
https://github.com/flutter/flutter/issues/35784
