### ISSUE TITLE
Rotate functionality isn't working.

### ISSUE THREAD

**Issue by DineshkumarThiran** [hnvn/flutter_image_cropper#12]
When i rotate the image within the modification page the rotation is happening. But when i click (tick) button the output is not being reflected.

**Comment by hnvn** [comment]
Which platform do you mention? Android or iOS or both of us?

**Comment by DineshkumarThiran** [comment]
I implemented in android platform..

**Comment by hnvn** [comment]
I can't reproduce this problem, I tried on my Sony Xperia Z5 (Android 7.1) and it worked well (rotate an image by 90 degrees)

**Comment by DineshkumarThiran** [comment]
Have you check without cropping the image only rotate the image , Can you able to get the rotated image  as the output.

**Comment by hnvn** [comment]
I tried, I see nothing wrong
