### ISSUE TITLE
Android Q Crash

### ISSUE THREAD

**Issue by williamborba** [hnvn/flutter_image_cropper#127]
someone with problem on android Q or 10?

**Comment by Dararii** [comment]
Yes, I can't pick an image from Gallery on Android Q. But if I pick an image from download folder it works like a charm.

**Comment by Zersya** [comment]
Yes, after cropping, it is said **unable to load asset**, but after I do the hot reload, It works again.

**Comment by alfinbi** [comment]
I have the sama problem, if I pick image from download folder it will works, but if I pick from other locations it has error

E/BitmapFactory( 4455): Unable to decode stream: java.io.FileNotFoundException: /storage/emulated/0/path/to/image.jpg: open failed: EACCES (Permission denied)

**Comment by UlanNurmatov** [comment]
I'm getting this  **unable to load asset** on the first launch, no matter from which folder I pick an image. 
It work only after hot reload. 
Did anyone solved this issue? @Zersya @alfinbi

**Comment by UlanNurmatov** [comment]
If someone is getting this error, and if you're trying to show the image which is located in the gallery or downloads, you could be using Image.asset instead of Image.file.

**Comment by AdrianSima** [comment]
There is still no solution for this problem?

Since upgrading targetSDK to 29 (which is now min requirement on Google Play) or 30, which uses sandboxed storage I can no longer crop images from DCIM/photo gallery.
