### ISSUE TITLE
Feature Request: MinWith and MinHeight

### ISSUE THREAD

**Issue by HerrNiklasRaab** [hnvn/flutter_image_cropper#13]
Hello and thanks for the great work you provided!

Is it possible to implement something like minWith and maxWith? Because now a user can crop the image infinit small?

Thanks,

Niklas

**Comment by hnvn** [comment]
I think it's better to check the dimension requirement in your own codes.

**Comment by HerrNiklasRaab** [comment]
Yes i understand, but this is the flow for the user at the moment:

1. Click on "Choose Image"
2. Croping the image
3. If it is to small for example 200x200 px, a error message is shown, for example:
"Your Picture is to small, please use a photo with bigger dimensions"
4. Click second time on "Choose Image"
5. Crop image with bigger dimension
6. Done

If it would be possible to declare a minWidth and minHeigt, the flow would be:

1. Click on "Choose Image"
2. Croping the image, with restricted zoom, or show error message in the cropper
3. Done

Hopefully you understand what I want to say.

Thanks again,
Niklas

**Comment by hnvn** [comment]
It sounds more friendly for users, but my plugin depends on native libraries, they take care of all of image manipulation steps, I only write a bit Dart codes to plug native side into flutter side, it's beyond me to modify those native libraries.

**Comment by HerrNiklasRaab** [comment]
Ok, leave this as open, i will ask the two native librarys for these features, the we can implement it here.

**Comment by hnvn** [comment]
It seems that the native library won't support it, we can do nothing now. I am going to close this issue.
