### ISSUE TITLE
error: cannot find symbol

### ISSUE THREAD

**Issue by guit4eva** [hnvn/flutter_image_cropper#133]
Getting the following error when trying to build the app:

```
/Users/me/.pub-cache/hosted/pub.dartlang.org/image_cropper-1.2.0/android/src/main/java/vn/hunghd/flutter/plugins/imagecropper/ImageCropperPlugin.java:78: error: cannot find symbol
    onAttachedToEngine(binding.getBinaryMessenger());
                              ^
  symbol:   method getBinaryMessenger()
  location: variable binding of type FlutterPluginBinding
1 error
Gradle task assembleRelease failed with exit code 1
```
I've tried flutter clean, problem persists.

**Comment by Mohammad-ezzidden** [comment]
same issue here

**Comment by KignorChan** [comment]
Same here!

**Comment by hnvn** [comment]
Have you migrated your android project to v2 embedding yet?
https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration

**Comment by sbd2** [comment]
Same here, judging by the date of the post I think we just ran into some kind of deadline from Google.

Please have a look at it, apps are not building anymore!

**Comment by hnvn** [comment]
Did you try on the [example](https://github.com/hnvn/flutter_image_cropper/tree/master/example) project? And be sure to use Flutter v1.12.13

**Comment by abdellatef94** [comment]
If you have Flutter 1.9.1+hotfix.4 just downgrade the plugin to image_cropper: 1.1.2  without  "^". It worked for me.

**Comment by hnvn** [comment]
You need to upgrade your project to Flutter v1.12.13 (or newer) to work with the latest version of this plugin
