### ISSUE TITLE
Unable to build the app with the below error

### ISSUE THREAD

**Issue by haroonkhan9426** [hnvn/flutter_image_cropper#135]
Note: /Users/eapple/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.12.10+2/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/eapple/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.12.10+2/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
/Users/eapple/.pub-cache/hosted/pub.dartlang.org/image_cropper-1.2.0/android/src/main/java/vn/hunghd/flutter/plugins/imagecropper/ImageCropperPlugin.java:78: error: cannot find symbol
    onAttachedToEngine(binding.getBinaryMessenger());
                              ^
  symbol:   method getBinaryMessenger()
  location: variable binding of type FlutterPluginBinding
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':image_cropper:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by hnvn** [comment]
upgrade your project to Flutter v1.12.13
