### ISSUE TITLE
MissingPluginException on Android

### ISSUE THREAD

**Issue by dzen1984** [hnvn/flutter_image_cropper#137]
On Android only.
On cold start - works correctly.
After close app by back pressed and then open from recent apps:

`MissingPluginException(No implementation found for method cropImage on channel plugins.hunghd.vn/image_cropper)`

**Comment by hnvn** [comment]
Have you tried on the [example project](https://github.com/hnvn/flutter_image_cropper/tree/master/example) yet?

**Comment by shinayser** [comment]
I as experiencing this right now.

My test is: open the crop, but back press withotu selecting a photo. Do it few times and it will eventally stop working, causing this missing plugin error.

It doesn't crash the app, but the cropping activity stops poping up.

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method cropImage on channel plugins.hunghd.vn/
image_cropper)
E/flutter (30083): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319)
E/flutter (30083): <asynchronous suspension>
E/flutter (30083): #1      ImageCropper.cropImage (package:image_cropper/src/cropper.dart:103)
E/flutter (30083): #2      _PhotoLoaderCardState._takePicture (package:mydenox_flutter/util_widgets/photo_loader_card.dart:350)
E/flutter (30083): <asynchronous suspension>
E/flutter (30083): #3      _PhotoLoaderCardState.build.<anonymous closure>.<anonymous closure> (package:mydenox_flutter/util_widgets/photo_loader_card.dart:170)
```

**Comment by likhithdevadiga** [comment]
Even I am facing same issue, Started to get it recently, everything was working fine before. 

E/flutter (28456): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method cropImage on channel plugins.hunghd.vn/image_cropper)
E/flutter (28456): #0 MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
E/flutter (28456):
E/flutter (28456): #1 ImageCropper.cropImage (package:image_cropper/src/cropper.dart:103:24)
E/flutter (28456):
E/flutter (28456): #2 _Screen._cropImage (package:tairos/screens/student_profile_screen.dart:847:43)
E/flutter (28456): #3 _Screen.getImage (package:tairos/screens/student_profile_screen.dart:842:7)
E/flutter (28456):
E/flutter (28456): #4 _Screen.showImage.... (package:tairos/screens/student_profile_screen.dart:822:33)
E/flutter (28456): #5 _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)
E/flutter (28456): #6 _InkResponseState.build. (package:flutter/src/material/ink_well.dart:789:36)
E/flutter (28456): #7 GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (28456): #8 TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
E/flutter (28456): #9 BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
E/flutter (28456): #10 BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:236:7)
E/flutter (28456): #11 GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter (28456): #12 GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
E/flutter (28456): #13 GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (28456): #14 GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (28456): #15 GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (28456): #16 GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (28456): #17 _rootRunUnary (dart:async/zone.dart:1138:13)
E/flutter (28456): #18 _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter (28456): #19 _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
E/flutter (28456): #20 _invoke1 (dart:ui/hooks.dart:273:10)
E/flutter (28456): #21 _dispatchPointerDataPacket (dart:ui/hooks.dart:182:5)
E/flutter (28456):

**Comment by njovy** [comment]
I think this happens in production if you didn't migrate to v2 embedding. It happened to me so I migrated it and it no longer happens

**Comment by shinayser** [comment]
> I think this happens in production if you didn't migrate to v2 embedding. It happened to me so I migrated it and it no longer happens

But this plugin is already migrated to v2, isn't it?

**Comment by hnvn** [comment]
>But this plugin is already migrated to v2, isn't it?

It already did but you also need to re-configure your android project. If you dont customize codes in android folder, you delete it and re-generate it by following command to migrate to v2 embedding:
`flutter create .` or `flutter create --kotlin .`

**Comment by shinayser** [comment]
> > But this plugin is already migrated to v2, isn't it?
> 
> It already did but you also need to re-configure your android project. If you dont customize codes in android folder, you delete it and re-generate it by following command to migrate to v2 embedding:
> `flutter create .` or `flutter create --kotlin .`

I have custom code. I have some firebase implementation and other small stuff. You know what can I do ?

**Comment by hnvn** [comment]
https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects

**Comment by shinayser** [comment]
I can confirm that upgrading the project to Embedding v2 fixes this issue! Thanks @hnvn and @njovy for your support.

**Comment by dzen1984** [comment]
After upgrading works correctly, thanks!

**Comment by likhithdevadiga** [comment]
> I think this happens in production if you didn't migrate to v2 embedding. It happened to me so I migrated it and it no longer happens

what is process in migrating to v2 embedding and wat are its effects?

**Comment by shinayser** [comment]
> > I think this happens in production if you didn't migrate to v2 embedding. It happened to me so I migrated it and it no longer happens
> 
> what is process in migrating to v2 embedding and wat are its effects?

If you read 4 messages above you will get what you need.
