### ISSUE TITLE
not find the crop icon in the example app?

### ISSUE THREAD

**Issue by wesamswetat** [hnvn/flutter_image_cropper#14]
i see closed issue of carlosbdw

i pick up an image first.
and when open image cropper with out crop icone

can you help
thanks

**Comment by hnvn** [comment]
#3

**Comment by hnvn** [comment]
There's no crop icon on toolbar because I set `ratioX` and `ratioY` for cropper in my example. It causes cropper work with fixed aspect ratio and doesn't allow user to change it, so it hide crop icon on toolbar. If you don't like it, just remove values of `ratioX` and `ratioY`
