### ISSUE TITLE
Portrait crop

### ISSUE THREAD

**Issue by JulieXeno** [hnvn/flutter_image_cropper#142]
There are only ratio for landscape. Is it possible to add portrait landscape ? Like 3:4 or 4:5 ?

**Comment by gopalfas1008** [comment]
any option to portrait  crop?

**Comment by cassioseffrin** [comment]
If you take to shot in portrait mode the options on iOS will be showed as portrait mode (3:4, 4:5, 9:16 and so on...), but If you turn your phone in landscape before the shot the options will be inverted automatically  to 4:3, 5:4, 16:9 and so on...
