### ISSUE TITLE
MissingPluginExecption

### ISSUE THREAD

**Issue by OlaleyeJumoke** [hnvn/flutter_image_cropper#155]
I'm getting the MissingPluginExecption as well but continuously every time the user leaves the app but doesn't fully close it. This is my use flow:

1. start the app
2. use the plugin functionality (everything works fine)
3. leave the app (eg. with home button or back button of your phone)
start the app again
4. `MissingPluginExecption` when trying to use the plugin function
If I close the app and restart it everything works fine but for that special usecase it doesn't.

`flutter clean` did not fix this.
Is there a way to fix this?

**Comment by fmatosqg** [comment]
may be related to #156

**Comment by mc10sw** [comment]
MissingPluginException(No implementation found for method cropImage on channel plugins.hunghd.vn/image_cropper)
i have same issue and i tested this on many devices of the samsung galaxy.

**Comment by OlaleyeJumoke** [comment]
> MissingPluginException(No implementation found for method cropImage on channel plugins.hunghd.vn/image_cropper)
> i have same issue and i tested this on many devices of the samsung galaxy.

I was able to solve the issue by upgrading to embedded v2.
sorry if this came late.

**Comment by karmazinkd** [comment]
> 
> 
> > MissingPluginException(No implementation found for method cropImage on channel plugins.hunghd.vn/image_cropper)
> > i have same issue and i tested this on many devices of the samsung galaxy.
> 
> I was able to solve the issue by upgrading to embedded v2.
> sorry if this came late.

Could you please elaborate a little bit more on this?
So you've just went through these steps in  [Upgrading pre 1.12 Android projects](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects)?
Did you do anything else?

I'm facing the same problem ( `image_cropper ^1.2.2` )

I've replaced `.MainActivity` with `io.flutter.embedding.android.FlutterActivity` in manifest, removed Application class from <application>, added <meta-data android:name="flutterEmbedding" android:value="2" />

Interestingly, that prior to migration to embedded v2 - this image_cropper 1.2.1 worked fine on the v1 with registrants...

**Comment by karmazinkd** [comment]
There is a PR https://github.com/hnvn/flutter_image_cropper/pull/163 that claims to fix MissingPluginExecption.
As I can see it adds `flutter_plugin_android_lifecycle` and handle both v1 and v2 versions.

@hnvn  could you please take a look at this PR? Thanks a lot!

**Comment by hnvn** [comment]
@karmazinkd , I don't why you are adding a lot of permissions checking codes in your PR. The plugin doesn't need those permissions

**Comment by karmazinkd** [comment]
> 
> 
> @karmazinkd , I don't why you are adding a lot of permissions checking codes in your PR. The plugin doesn't need those permissions

It's not mine :) I just noticed that someone PRs your plugin to fix MissingPluginExecption.

and I do have MissingPluginExecption even though I migrated to v2 embedded, so I'm wondering if you can take a look at it.

**Comment by hnvn** [comment]
Could you give me a project to help me reproduce this issue?

**Comment by zaferyus** [comment]
I am facing the same issue with latest version 1.2.2
E/flutter (27913): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method cropImage on channel plugins.hunghd.vn/image_cropper)
E/flutter (27913): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter (27913): <asynchronous suspension>
E/flutter (27913): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter (27913): #2      ImageCropper.cropImage (package:image_cropper/src/cropper.dart:102:24)

There is no problem at the version 1.2.1

**Comment by mrkobby** [comment]
I'm having the same issue. It doesn't crash the app but the cropper fails to open. I have tried `flutter clean` and `flutter pub repair`. But it is still not working. I even proceeded to migrate my [android project to v2 embedding](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects), but it's giving the same error.

I tried [this fix](https://github.com/hnvn/flutter_image_cropper/pull/162/commits/edca7fb40e9fdbf8abd4e2f6d14f4415bcb4412a) , but it's still not working. Any working solution or suggestions will be appreciated.

Here is my error message:
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method cropImage on channel plugins.hunghd.vn/image_cropper)
E/flutter (10219): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter (10219): <asynchronous suspension>
E/flutter (10219): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter (10219): #2      ImageCropper.cropImage (package:image_cropper/src/cropper.dart:102:24)
E/flutter (10219): <asynchronous suspension>
E/flutter (10219): #3      _ProfileChangePhotoState._cropImage (package:myapp/pages/profile/profileChangePhoto.dart:305:43)
E/flutter (10219): #4      _ProfileChangePhotoState.build.<anonymous closure> (package:myapp/pages/profile/profileChangePhoto.dart:107:40)
E/flutter (10219): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:779:19)
E/flutter (10219): #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:862:36)
E/flutter (10219): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (10219): #8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:504:11)
E/flutter (10219): #9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282:5)
E/flutter (10219): #10     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:217:7)
E/flutter (10219): #11     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:475:9)
E/flutter (10219): #12     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
E/flutter (10219): #13     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
E/flutter (10219): #14     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
E/flutter (10219): #15     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
E/flutter (10219): #16     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
E/flutter (10219): #17     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter (10219): #18     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (10219): #19     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (10219): #20     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (10219): #21     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (10219): #22     _rootRunUnary (dart:async/zone.dart:1196:13)
E/flutter (10219): #23     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter (10219): #24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
E/flutter (10219): #25     _invoke1 (dart:ui/hooks.dart:275:10)
E/flutter (10219): #26     _dispatchPointerDataPacket (dart:ui/hooks.dart:184:5)``
```

**Comment by mrkobby** [comment]
> 
> 
> I'm having the same issue. It doesn't crash the app but the cropper fails to open. I have tried `flutter clean` and `flutter pub repair`. But it is still not working. I even proceeded to migrate my [android project to v2 embedding](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects), but it's giving the same error.
> 
> I tried [this fix](https://github.com/hnvn/flutter_image_cropper/pull/162/commits/edca7fb40e9fdbf8abd4e2f6d14f4415bcb4412a) , but it's still not working. Any working solution or suggestions will be appreciated.
> 
> Here is my error message:
> 
> ```
> [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method cropImage on channel plugins.hunghd.vn/image_cropper)
> E/flutter (10219): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
> E/flutter (10219): <asynchronous suspension>
> E/flutter (10219): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
> E/flutter (10219): #2      ImageCropper.cropImage (package:image_cropper/src/cropper.dart:102:24)
> E/flutter (10219): <asynchronous suspension>
> E/flutter (10219): #3      _ProfileChangePhotoState._cropImage (package:myapp/pages/profile/profileChangePhoto.dart:305:43)
> E/flutter (10219): #4      _ProfileChangePhotoState.build.<anonymous closure> (package:myapp/pages/profile/profileChangePhoto.dart:107:40)
> E/flutter (10219): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:779:19)
> E/flutter (10219): #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:862:36)
> E/flutter (10219): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
> E/flutter (10219): #8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:504:11)
> E/flutter (10219): #9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282:5)
> E/flutter (10219): #10     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:217:7)
> E/flutter (10219): #11     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:475:9)
> E/flutter (10219): #12     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
> E/flutter (10219): #13     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
> E/flutter (10219): #14     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
> E/flutter (10219): #15     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
> E/flutter (10219): #16     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
> E/flutter (10219): #17     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
> E/flutter (10219): #18     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
> E/flutter (10219): #19     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
> E/flutter (10219): #20     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
> E/flutter (10219): #21     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
> E/flutter (10219): #22     _rootRunUnary (dart:async/zone.dart:1196:13)
> E/flutter (10219): #23     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
> E/flutter (10219): #24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
> E/flutter (10219): #25     _invoke1 (dart:ui/hooks.dart:275:10)
> E/flutter (10219): #26     _dispatchPointerDataPacket (dart:ui/hooks.dart:184:5)``
> ```

[`This branch` ](https://github.com/hnvn/flutter_image_cropper/pull/163#pullrequestreview-425774879) fixed it!!!

**Comment by hnvn** [comment]
Please check v1.2.3

**Comment by hnvn** [comment]
Any update? Shall I close this issue?

**Comment by mc10sw** [comment]
okay,
I have checked 1.2.3 update fixed that issue.
thank you for your quick update.
