### ISSUE TITLE
ImageCropper.cropImage only returns jpg

### ISSUE THREAD

**Issue by thedigitalpro** [hnvn/flutter_image_cropper#168]
Even if I pass in a file which is of type PNG and set compressFormat: ImageCompressFormat.png the returned file is a JPG. 

Does ImageCropper support a PNG output?

**Comment by kaushalsitapara** [comment]
use this https://github.com/hnvn/flutter_image_cropper/pull/184/commits/1e07c7717f62713f9f7752343ea52dafa66af270

**Comment by hnvn** [comment]
fixed in v1.3.1
