### ISSUE TITLE
i can't able to import this package.

### ISSUE THREAD

**Issue by anandsubbu007** [hnvn/flutter_image_cropper#174]
![image](https://user-images.githubusercontent.com/55450843/85134565-56209c80-b25a-11ea-9a42-615154dd5196.png)

i run flutter pub get

but it is not responding

**Comment by Henzelix** [comment]
Have you added this code to your AndroidManifest.xml?

`<activity
    android:name="com.yalantis.ucrop.UCropActivity"
    android:screenOrientation="portrait"
    android:theme="@style/Theme.AppCompat.Light.NoActionBar"/>`
