### ISSUE TITLE
style/Theme.AppCompat.Light.NoActionBar) not found.

### ISSUE THREAD

**Issue by lblblong** [hnvn/flutter_image_cropper#18]
F:\xxx\xxx\xxxx\app\build\app\intermediates\manifests\full\debug\AndroidManifest.xml:57: AAPT: error: resource style/Theme.AppCompat.Light.NoActionBar (aka com.bk.xxxx:style/Theme.AppCompat.Light.NoActionBar) not found.

**Comment by lblblong** [comment]
already solved
Seems to be the reason for the low version of gradle
After I copied the gradle configuration of the new project, the problem was solved.

**Comment by lblblong** [comment]
Sorry, time is too far away and the code for this project has been lost

**Comment by lblblong** [comment]
> > F:\xxx\xxx\xxxx\app\build\app\intermediates\manifests\full\debug\AndroidManifest.xml:57: AAPT: error: resource style/Theme.AppCompat.Light.NoActionBar (aka com.bk.xxxx:style/Theme.AppCompat.Light.NoActionBar) not found.
> 
> HI The same issue i am facing even after setting the gradle . Can you tell me what version you set for this

Sorry, time is too far away and the code for this project has been lost

**Comment by aruny121** [comment]
oh ok , sorry i just notices you posted this in 2018 👍
