### ISSUE TITLE
New FATAL EXCEPTION: main error, app crashes

### ISSUE THREAD

**Issue by chapmacl** [hnvn/flutter_image_cropper#189]
Using 1.3.1 on Flutter 1.20.2 (also had this issue using a beta version 1.22). 

E/AndroidRuntime(29226): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=69, result=0, data=null} to activity {com.app.app/com.app.app.MainActivity}: java.lang.IllegalStateException: Reply already submitted

with this being on the stack: (package:image_cropper/src/cropper.dart:102:24)

final String resultPath =
        await _channel.invokeMethod('cropImage', arguments); //error caused here
    return resultPath == null ? null : new File(resultPath);

**Comment by chapmacl** [comment]
added this to manifest:
<activity
    android:name="com.yalantis.ucrop.UCropActivity"
    android:screenOrientation="portrait"
    android:theme="@style/Theme.AppCompat.Light.NoActionBar"/>

Although the plugin was working fine for the past month on an older version of Flutter without this, adding this fixed it. I expect this was the issue

**Comment by Quietly-20201113** [comment]
未解决问题
