### ISSUE TITLE
uCrop new design

### ISSUE THREAD

**Issue by sergiyvergun** [hnvn/flutter_image_cropper#193]
uCrop was redesigned in 2.2.4 and now looks this way 

https://github.com/Yalantis/uCrop/blob/develop/preview.gif

Even though flutter_image_cropper uses uCrop 2.2.6 , it still has old interface.

How to use uCrop with new interface?

**Comment by hnvn** [comment]
You are wrong about the new design, the preview image is actually the old design not the new one
