### ISSUE TITLE
Need circular Image cropping

### ISSUE THREAD

**Issue by edwin-alvarez** [hnvn/flutter_image_cropper#201]
Is there a way to cropping using a circular option directly on image_cropper

Refer to #91 
it looks like now both Ucrop and TOCropViewController support the circular option:

#Yalantis/uCrop#680
#TimOliver/TOCropViewController#197

**Comment by edwin-alvarez** [comment]
nevermind I found I can use 
`
cropStyle: CropStyle.circle`

**Comment by ganeshchenniah** [comment]
Hi edwin ,
I m also looking for circular crop, i have upgrdaed ucrop and image_cropper library to latest , still circular crop is not happening . 

Below is the code i have used , please suggest if i had missed any. 
Thanks 
File cropped = await ImageCropper.cropImage(
sourcePath: _photoUrlFile.path,
compressQuality: 99,
cropStyle: CropStyle.circle,
compressFormat: ImageCompressFormat.png,
// aspectRatioPresets: [CropAspectRatioPreset.square],
// maxWidth: 1200,
// maxHeight: 1400,
androidUiSettings: AndroidUiSettings(
toolbarColor: Colors.orange,
toolbarWidgetColor: Colors.white,
lockAspectRatio: false,
toolbarTitle: 'Crop It'),
);
