### ISSUE TITLE
Require 6 and 8 Edge Crop

### ISSUE THREAD

**Issue by Sparshagarwal12** [hnvn/flutter_image_cropper#205]
Hello Sir, This Image Cropper package is really incredible but if it has 6 or 8 points to crop the image then it will be very useful

So, can you please add this feature.

**Comment by hnvn** [comment]
The feature is out of capability of this plugin. As I write on README, the plugin only exposes API of two native libraries (uCrop and TOCropViewController) to Flutter by using PlatformChannel. If these library don't support the feature you're expected, I can do nothing.
