### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by chenyongze** [hnvn/flutter_image_cropper#216]
lib/pages/ModifyAvatorPage.dart:35:7: Error: No named parameter with the name 'ratioX'.
      ratioX: 1.0,
      ^^^^^^
../../../../.pub-cache/hosted/pub.flutter-io.cn/image_cropper-1.3.1/lib/src/cropper.dart:62:23: Context: Found this candidate, but the arguments don't match.
  static Future<File> cropImage({
                      ^^^^^^^^^

Command PhaseScriptExecution failed with a nonzero exit code

![image](https://user-images.githubusercontent.com/4531363/97970738-f5ef5900-1dfc-11eb-930b-5485996e9491.png)

**Comment by chenyongze** [comment]
sorry

**Comment by shumaise** [comment]
having same issue, while trying to build an app developed in flutter older version. how did you fix it.
