### ISSUE TITLE
modify bottom menuText

### ISSUE THREAD

**Issue by JGNS** [hnvn/flutter_image_cropper#229]
how to modify the bottom menuText?default is Crop,Rotate,Scale,hope can do this.thanks.

**Comment by zhouxiaofu** [comment]
Have you solved the problem? I have the same problem

**Comment by mbfakourii** [comment]
@hnvn
please Fix

**Comment by axiaofang666** [comment]
@hnvn please Fix

**Comment by hnvn** [comment]
I guest that you guys are mentioning the Android version of this plugin. If you have a look at the native library that this plugin is based on (uCrop), you can see that there's no option to change these titles directly but we can do it indirectly by overriding these text content in xml file. Have a look at this file: [ucrop/src/main/res/values/strings.xml](https://github.com/Yalantis/uCrop/blob/1a7653e102414d805ff13095efb049f95de594f1/ucrop/src/main/res/values/strings.xml). So you can create the same strings.xml file in your own android project and provide your new text value for them.
