### ISSUE TITLE
How to change ActionBar's color

### ISSUE THREAD

**Issue by wiiiky** [hnvn/flutter_image_cropper#23]
Thanks for your work in Advance. but how can I change the primaryColor of UCropActivity?

I have tried changing the theme of UCropActivity, like

```
        <activity
            android:name="com.yalantis.ucrop.UCropActivity"
            android:screenOrientation="portrait"
            android:theme="@style/CustomTheme"/>
```

but it didn't work.

**Comment by hnvn** [comment]
Using `toolbarColor ` property when you call to `ImageCropper`, see code document to get more detail

**Comment by wiiiky** [comment]
@hnvn it works. Thanks.
