### ISSUE TITLE
App crashes : java.lang.RuntimeException: Unable to start activity ComponentInfo

### ISSUE THREAD

**Issue by amit-onappr** [hnvn/flutter_image_cropper#231]
**App crashes when using image cropper.**

I am using 
```
image_cropper: ^1.3.1
compileSdkVersion 29
flutter SDK : 1.22.5
```
FATAL EXCEPTION: main
E/AndroidRuntime(26939): Process: in.shoopy.business, PID: 26939
E/AndroidRuntime(26939): java.lang.RuntimeException: Unable to start activity ComponentInfo{in.shoopy.business/com.yalantis.ucrop.UCropActivity}: android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class androidx.appcompat.widget.Toolbar
E/AndroidRuntime(26939): at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3037)
E/AndroidRuntime(26939): at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3172)
E/AndroidRuntime(26939): at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
E/AndroidRuntime(26939): at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
E/AndroidRuntime(26939): at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
E/AndroidRuntime(26939): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1906)
E/AndroidRuntime(26939): at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(26939): at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(26939): at android.app.ActivityThread.main(ActivityThread.java:6863)
E/AndroidRuntime(26939): at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(26939): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
E/AndroidRuntime(26939): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/AndroidRuntime(26939): Caused by: android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class androidx.appcompat.widget.Toolbar

**Comment by amit-onappr** [comment]
Found solution, nothing related. 

```
subprojects {
        project.configurations.all {
            resolutionStrategy.eachDependency { details ->
                if (details.requested.group == 'com.android.support'
                        && !details.requested.name.contains('multidex') ) {
                    details.useVersion "27.1.1"
                }

                if (details.requested.group == 'androidx.core'
                        && !details.requested.name.contains('androidx') ) {
                    details.useVersion "1.1.0"
                }
            }
        }
    }
```

**Comment by jomazao** [comment]
Similar issue on nexus 5x Android 8.1.0
Fatal Exception: java.lang.RuntimeException: Unable to start activity ```
ComponentInfo{com.kargoo.kargooapp/com.yalantis.ucrop.UCropActivity}: android.view.InflateException: Binary XML file line #27: Binary XML file line #46: Error inflating class ImageView
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by zynhrus** [comment]
> 

I got the same error, and it happen only on nexus 5x Android 8.1.0 too. Do you have any update or have you solved it?

**Comment by zynhrus** [comment]
> Similar issue on nexus 5x Android 8.1.0 Fatal Exception: java.lang.RuntimeException: Unable to start activity
> 
> ```
> ComponentInfo{com.kargoo.kargooapp/com.yalantis.ucrop.UCropActivity}: android.view.InflateException: Binary XML file line #27: Binary XML file line #46: Error inflating class ImageView
>        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
>        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
>        at android.app.ActivityThread.-wrap11(ActivityThread.java)
>        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
>        at android.os.Handler.dispatchMessage(Handler.java:106)
>        at android.os.Looper.loop(Looper.java:164)
>        at android.app.ActivityThread.main(ActivityThread.java:6494)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
> ```

I got the same error, and it happen only on nexus 5x Android 8.1.0 too. Do you have any updates or have you solved it?

**Comment by marcotta** [comment]
I see the ticket is closed,
I am using 

```yaml
image_cropper: ^8.0.2
flutter: 3.24.3
```

and I can see the error logged from a `Nexus 5X` with `Android 11`.

Any hints on how to prevent it?
