### ISSUE TITLE
Migrate to AndroidX

### ISSUE THREAD

**Issue by HarishKanth** [hnvn/flutter_image_cropper#25]

**Comment by hnvn** [comment]
What's the matter in AndroidX?

**Comment by HarishKanth** [comment]
I migrated my app to AndroidX. I faced issues in image_cropper. I had to manually migrate this library to AndroidX to solve the issue.

Check [this](https://developer.android.com/topic/libraries/support-library/)

**Comment by blaneyneil** [comment]
a recent Flutter upgrade forced everyone to target sdk 28, and to set the following:

android.useAndroidX=true
android.enableJetifier=true 

the latter being necessary if you use any Firestore plugins.  but the build is now throwing this:

...0.0.9/android/src/main/java/vn/hunghd/flutter/plugins/imagecropper/ImageCropperDelegate.java:8: error: package android.support.annotation does not exist
import android.support.annotation.ColorInt;
                                 ^
...0.0.9/android/src/main/java/vn/hunghd/flutter/plugins/imagecropper/ImageCropperDelegate.java:110: error: cannot find symbol
    private int darkenColor(@ColorInt int color) {
                             ^
  symbol:   class ColorInt
  location: class ImageCropperDelegate
...0.0.9/android/src/main/java/vn/hunghd/flutter/plugins/imagecropper/ImageCropperDelegate.java:109: error: cannot find symbol
    @ColorInt
     ^
  symbol:   class ColorInt
  location: class ImageCropperDelegate
3 errors

**Comment by cokn-s** [comment]
I am also experiencing this issue, @HarishKanth any more information on how you corrected it?

**Comment by JotaFerreira** [comment]
this is really necessary, I had to remove the lib provisionally to continue working

**Comment by HarishKanth** [comment]
@cokn-s 

1) Open Android Folder of image_cropper in Android Studio

![image](https://user-images.githubusercontent.com/12816184/52281116-685eab00-2983-11e9-9e96-cdee8d584727.png)

Ignore errors if you see any.

2) Update `compileSdkVersion` and `targetSdkVersion` to `28`

3) Go to Refractor-> Migrate to AndroidX

This should do it.

Refer [this comment](https://github.com/flutter/flutter/issues/27128#issuecomment-457918930), if you face any issue

**Comment by hnvn** [comment]
I haven't ever used AndroidX. I will have a look at it when I come back from my vacation.

**Comment by cokn-s** [comment]
@HarishKanth 

I was unable to follow what you said because every time I try to run the Refractor -> Migrate to AndroidX it errors and tell me to update my compileSDK to at least 28 even though it already is.  I tried going through all the packages I am using and making sure they are at 28 as well but I was still getting the error.

I was able to correct the issue manually however by going into the android folder of the image cropper and changing the import to: `import androidx.annotation.ColorInt;`

Thanks for your time and help!

**Comment by blaneyneil** [comment]
can confirm that @cokn-s solution:

```
//import android.support.annotation.ColorInt;
import androidx.annotation.ColorInt;
```

from ImageCropperDelegate.java works.

**Comment by msw333** [comment]
@cokn-s @blaneyneil - i am just a complete beginner. Where do I find the file and the 'android folder' of image cropper, which I have to change in android studio ;-)? path?

**Comment by blaneyneil** [comment]
open up the Flutter Plugins folder, then image_cropper > android > src > main > java > vn > hunghd > flutter > plugins > imagecropper > ImageCropperDelegate.java

**Comment by gustavobrian** [comment]
please, publish AndroidX version.
Thanks

**Comment by hnvn** [comment]
I will work on it this weekend.

**Comment by wamphlett** [comment]
Following the suggestions above, the below actions got me up and running again: 

`<project>/android/gradle.properties`
```diff
+ android.useAndroidX=true
+ android.enableJetifier=true
```
`<image_cropper-0.0.9>/android/src/main/java/vn/hunghd/flutter/plugins/imagecropper/ImageCropperDelegate.java`

```diff
- import android.support.annotation.ColorInt;
+ import androidx.annotation.ColorInt;
```

I also did the below although I am not particularly sure it was neccesary, either way, Im back up and running but it would be good to get this packages updated as soon as possible.

`<image_cropper-0.0.9>/android/gradle.properties`
```diff
+ android.useAndroidX=true
+ android.enableJetifier=true
```

**Comment by bijoya-banik** [comment]
- import android.support.annotation.ColorInt;
+ import androidx.annotation.ColorInt;

this solution works nicely, thank u :)
