### ISSUE TITLE
change android library

### ISSUE THREAD

**Issue by DJafari** [hnvn/flutter_image_cropper#26]
is possible change android library to this one ?

https://github.com/ArthurHub/Android-Image-Cropper

current library is ugly and big restriction is : user can't select custom ratio
i don't have any restriction to ratio of image

**Comment by sunnyseeds** [comment]
I would support this change.

**Comment by hnvn** [comment]
I don't have plan to change native libraries. Each library has its own pro and cons. I think the current library still works well with cropping image purpose
