### ISSUE TITLE
Disable double tap aspect ratio change 

### ISSUE THREAD

**Issue by cavedweller** [hnvn/flutter_image_cropper#263]
First of all i would like to thank you for the awesome package you have provided.

### Issue
When the aspect ratio has been selected, then the asect ratio is again taped it switches.

I would just like to know how to dissable this. I am using an android.

I have attached a video of what i mean.

https://user-images.githubusercontent.com/70595829/118878611-0924ca80-b8f0-11eb-90c0-222b7662e725.mp4

**Comment by cavedweller** [comment]
# Issue

@hnvn , @yendacoder , @cwyu-Ivan , @defuncart  I am still having this issue regarding the aspect ratios switching when tapping on them twice (Please see above video) is there any work around?

```Dart
                      XFile? file = await _picker.pickImage(source: ImageSource.gallery);
                      if (file != null) {
                        CroppedFile? croppedFile = await ImageCropper().cropImage(
                          sourcePath: file.path,
                          aspectRatioPresets: [
                            CropAspectRatioPreset.ratio3x2,
                            CropAspectRatioPreset.original,
                            CropAspectRatioPreset.square,
                            CropAspectRatioPreset.ratio4x3,
                            CropAspectRatioPreset.ratio16x9
                          ],
                          uiSettings: [
                            AndroidUiSettings(
                                activeControlsWidgetColor: Theme.of(context).primaryColor,
                                toolbarTitle: 'Edit',
                                toolbarColor: Theme.of(context).appBarTheme.backgroundColor,
                                toolbarWidgetColor: Theme.of(context).textTheme.bodyMedium!.color!,
                                initAspectRatio: CropAspectRatioPreset.original,
                                lockAspectRatio: true),
                          ],
                        );
                      }
```

## Expected outcome
I would like to disable the aspect ratios switching if they are double tapped 

Any assistance would be greatly appreciated 😎

**Comment by hnvn** [comment]
The behavior comes from the native library, I am afraid that I can do nothing from Flutter codes, you may as well go to the native library repo and ask for help, in this repo, I only use Platform channel to expose Dart API to call to native libraries, if you can find a proper API to change this behavior, I can expose it to Dart codes.
