### ISSUE TITLE
Missing [AspectRatio] class export at beta release

### ISSUE THREAD

**Issue by VB10** [hnvn/flutter_image_cropper#323]
Hello dear team, I'm trying to use image_cropper-2.0.0-beta version, but it has a bit problem. I cannot access AspectRatio class because this version only export these classes. Could you fix this problem of send a new version.(Actually I checked master, no any issues there)

First need this:
<img width="302" alt="Screen Shot 2022-03-18 at 00 33 43" src="https://user-images.githubusercontent.com/17102578/158899142-a4e2b6f7-aff9-40f3-8cfb-37a75490d65d.png">

Beta version is showing like this:
<img width="743" alt="Screen Shot 2022-03-18 at 00 34 15" src="https://user-images.githubusercontent.com/17102578/158899335-00f9c697-d165-4809-a830-ffc50f298076.png">

Thank. u!

**Comment by hnvn** [comment]
Thanks for your feedback. It would fixed on v2.0.0-beta.2
