### ISSUE TITLE
Web plugin is not registered correctly

### ISSUE THREAD

**Issue by cmalex23** [hnvn/flutter_image_cropper#330]
Hello, great work on the new web version.
But in the current form it's not registered in generated_plugin_registrant.dart

You need to add these changed to `pubspec.yaml` In `image_cropper_for_web`:

    flutter:
          plugin:
            implements: image_cropper
            platforms:
              web:
                pluginClass: ImageCropperPlugin
                fileName: image_cropper_for_web.dart

EDIT: And also the `WebUiSettings` class is not exported from `'package:image_picker/image_picker.dart'` currently

Thanks!

**Comment by hnvn** [comment]
Thanks for you feedback, could you create a PR for it?

**Comment by c-seeger** [comment]
need it also prepared a PR

**Comment by c-seeger** [comment]
:heart:

**Comment by hnvn** [comment]
Released new version 2.0.1
