### ISSUE TITLE
js + css files not found

### ISSUE THREAD

**Issue by c-seeger** [hnvn/flutter_image_cropper#333]
currently i'm getting 404 for all js, css files (croppie.css, croppie.min.js, etc) it looks like they were missing in the repository.

Also to use WebUiSettings i need to import `image_cropper_for_web` is it possible to export the web settings in `image_cropper` itself?

**Comment by hnvn** [comment]
`WebSettings` class includes some JS objects, it cannot be exported with `image_cropper` otherwise the codes for mobile will be broken.

**Comment by hnvn** [comment]
I created an example: https://github.com/hnvn/image_cropper_example

**Comment by sknew93** [comment]
https://github.com/hnvn/flutter_image_cropper/issues/334#issuecomment-1120966756
Try this,

**Comment by c-seeger** [comment]
Hi again, found some time to test it out. Still have the same issue. I'm using `flutter build web` and it seems that the javascript files are not exported as assets correctly when building

**Comment by c-seeger** [comment]
The fix provided by @sknew93 works but the package should export them correctly by itself.

**Comment by hnvn** [comment]
Sorry guys, import JS library part in README document is wrong, it should be:
````
<!-- Croppie -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/croppie/2.6.5/croppie.css" />
  <script defer src="https://cdnjs.cloudflare.com/ajax/libs/exif-js/2.3.0/exif.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/croppie/2.6.5/croppie.min.js"></script>
````

**Comment by c-seeger** [comment]
@hnvn I do like @sknew93 solution since it lets you serve the files without the need of cloudflare (maybe you can add this in addition). 
I've also seen that you can somehow export these files the way you intended it, using `assets/packages/<package-name>/...`

https://github.com/imtoori/CountryCodePicker does this. Maybe there is a hint. Would be even cooler if this would be the default.
