### ISSUE TITLE
Flutter Web Error in release or live(after deploy) 

### ISSUE THREAD

**Issue by sknew93** [hnvn/flutter_image_cropper#334]
Hi, 
This is the error shown in the console in release and in the live site.

`
js_helper.dart:1137 
    Uncaught TypeError: self.Croppie is not a constructor
    at image_cropper_for_web.dart:120:29
    at cf0.a (async_patch.dart:317:19)
    at cf0.$2 (async_patch.dart:342:23)
    at Object.p (async_patch.dart:247:3)
    at b0k.beE (image_cropper_for_web.dart:91:20)
    at b0k.xV (image_cropper_for_web.dart:91:20)
    at cropper.dart:86:21
    at cf0.a (async_patch.dart:317:19)
    at cf0.$2 (async_patch.dart:342:23)
    at cdm.$1 (async_patch.dart:293:19)
`

**Comment by sknew93** [comment]
[
![image](https://user-images.githubusercontent.com/64492651/167388174-3b9a71c4-5d8b-44ad-a1de-e0a10028de49.png)
](url)

**Comment by hnvn** [comment]
Can you try on other Web browser like Google Chrome?

**Comment by sknew93** [comment]
simply copying those files;
![image](https://user-images.githubusercontent.com/64492651/167398754-44ce94dc-5dae-473d-becd-f4e7e03e6c8e.png)

to the main web folder and changing the location in the index.html. 
![image](https://user-images.githubusercontent.com/64492651/167398847-967ff81a-d8f8-45db-9a8c-5f0c8e30adb1.png)
did the trick.
Works now!
