### ISSUE TITLE
plugins.hunghd.vn/image_cropper request fails

### ISSUE THREAD

**Issue by kvfun** [hnvn/flutter_image_cropper#34]
![image](https://user-images.githubusercontent.com/15116804/56087993-98f22200-5ea9-11e9-8339-3cedb9f7addc.png)

**Comment by hnvn** [comment]
It looks like there's something wrong in your setting project that cause this plugin isn't registered into your application. You might have a look at `GeneratedPluginRegistrant.java` and make sure that `ImageCropper` is registered in this file.
