### ISSUE TITLE
Web version mobile view EdgeInsets waste a lot of space

### ISSUE THREAD

**Issue by c-seeger** [hnvn/flutter_image_cropper#343]
Using the web version with a mobile view results in a lot of spacing lost on the sides.

probably due to
https://github.com/hnvn/flutter_image_cropper/blob/88a9ab6c724a79e0c44b00d290f59b5cc84b5366/image_cropper_for_web/lib/src/cropper_page.dart#L47

can we make this configurable in some way?

**Comment by hnvn** [comment]
This space dues to adjust position of zoom controller and rotate button, these controllers are html element and out of Flutter widget, I have to put more space into Flutter widget to adopt these controllers in UI. If you cannot use `CropperPage` directly, you can provider your customize page view by using `CropperRouteBuilder`
