### ISSUE TITLE
image Compression

### ISSUE THREAD

**Issue by jonex41** [hnvn/flutter_image_cropper#348]
is it possible to only use the compresion part of the code

**Comment by hnvn** [comment]
Bạn không nên làm điều đó, plugin không có ý định hỗ trợ nó, vì vậy nó sẽ xảy ra sự cố hoặc hành vi không mong muốn nếu bạn cố gắng làm theo cách đó.

**Comment by jonex41** [comment]
ok cảm ơn bạn, thư viện tốt đẹp
