### ISSUE TITLE
Is there any feature where i can select my crop ratios

### ISSUE THREAD

**Issue by devloperAditya** [hnvn/flutter_image_cropper#35]
Have this library implemented the feature of selecting the crop ratio as it is there in android (for eg: there are 1:1, 3:4, 3:2, 16:9 and original but i just need two out of them)

Thanks in advance !!!

**Comment by MiguelSOliveira** [comment]
Any news on this?

**Comment by hnvn** [comment]
in v1.1.0 now, you can customize the aspect ratio reset in menu list.
