### ISSUE TITLE
IOS Error

### ISSUE THREAD

**Issue by alixumer** [hnvn/flutter_image_cropper#358]
[!] CocoaPods could not find compatible versions for pod "TOCropViewController":
  In Podfile:
    image_cropper (from `.symlinks/plugins/image_cropper/ios`) was resolved to 0.0.4, which depends on
      TOCropViewController (~> 2.6.1)

None of your spec sources contain a spec satisfying the dependency: `TOCropViewController (~> 2.6.1)`.

**Comment by hnvn** [comment]
Try these commands:
```bash
cd ios
pod deintegrate
rm -rf Podfile.lock
pod install --repo-update
```
