### ISSUE TITLE
copy to other project App Crashes when crop icon is clicked.

### ISSUE THREAD

**Issue by qq329401134** [hnvn/flutter_image_cropper#36]
I/asdfasdfsdafas(20717): Rejecting re-init on previously-failed class java.lang.Class<com.yalantis.ucrop.UCropFragment>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/app/Fragment;
I/asdfasdfsdafas(20717):   at com.yalantis.ucrop.UCrop com.yalantis.ucrop.UCrop.of(android.net.Uri, android.net.Uri) (UCrop.java:64)
I/asdfasdfsdafas(20717):   at void vn.hunghd.flutter.plugins.imagecropper.ImageCropperDelegate.startCrop(io.flutter.plugin.common.MethodCall, io.flutter.plugin.common.MethodChannel$Result) (ImageCropperDelegate.java:84)
I/asdfasdfsdafas(20717):   at void vn.hunghd.flutter.plugins.imagecropper.ImageCropperPlugin.onMethodCall(io.flutter.plugin.common.MethodCall, io.flutter.plugin.common.MethodChannel$Result) (ImageCropperPlugin.java:36)
I/asdfasdfsdafas(20717):   at void io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(java.nio.ByteBuffer, io.flutter.plugin.common.BinaryMessenger$BinaryReply) (MethodChannel.java:201)
I/asdfasdfsdafas(20717):   at void io.flutter.view.FlutterNativeView$PlatformMessageHandlerImpl.handleMessageFromDart(java.lang.String, byte[], int) (FlutterNativeView.java:188)
I/asdfasdfsdafas(20717):   at void io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(java.lang.String, byte[], int) (FlutterJNI.java:202)
I/asdfasdfsdafas(20717):   at void android.os.MessageQueue.nativePollOnce(long, int) (MessageQueue.java:-2)
I/asdfasdfsdafas(20717):   at android.os.Message android.os.MessageQueue.next() (MessageQueue.java:326)
I/asdfasdfsdafas(20717):   at void android.os.Looper.loop() (Looper.java:160)
I/asdfasdfsdafas(20717):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6669)
I/asdfasdfsdafas(20717):   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/asdfasdfsdafas(20717):   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:493)
I/asdfasdfsdafas(20717):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:858)
I/asdfasdfsdafas(20717): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.app.Fragment" on path: DexPathList[[zip file "/data/app/com.example.asdfasdfsdafasd-f8viCtNfqNa5E-Tb-v5wcg==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.asdfasdfsdafasd-f8viCtNfqNa5E-Tb-v5wcg==/lib/x86, /data/app/com.example.asdfasdfsdafasd-f8viCtNfqNa5E-Tb-v5wcg==/base.apk!/lib/x86, /system/lib]]
I/asdfasdfsdafas(20717):   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:134)
I/asdfasdfsdafas(20717):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String,
boolean) (ClassLoader.java:379)
I/asdfasdfsdafas(20717):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String)
(ClassLoader.java:312)

in AndroidManifest.xml
![image](https://user-images.githubusercontent.com/38587734/56302053-93c3fa00-616b-11e9-917a-c27b43ddf35c.png)
![image](https://user-images.githubusercontent.com/38587734/56302063-97f01780-616b-11e9-9854-1aa43b81623b.png)
@hnvn 不知道为什么会这样，希望可以得到你的帮助谢谢了

**Comment by hnvn** [comment]
What about your gradle.build?

**Comment by sanyamjain65** [comment]
I am facing the same problem.....could you please tell me how to fix this?

**Comment by braysonjohn148** [comment]
i had the same issue... "flutter clean" saved my day, just make sure you added the activity in manifest file,  moved to android X, then you clean the project. Worked for me.
