### ISSUE TITLE
DuplicateClasses while building for android devices

### ISSUE THREAD

**Issue by t-bolt** [hnvn/flutter_image_cropper#366]
When i try to build my app for android devices, i keep getting this error that makes some reference to duplicate classes in Yalantis(UCrop) 

Debug Console message below-->
     java.lang.RuntimeException: Duplicate class com.yalantis.ucrop.UCrop found in modules jetified-pictureselector-v2.7.3-rc10-runtime.jar (io.github.lucksiege:pictureselector:v2.7.3-rc10) and jetified-ucrop-2.2.8-runtime.jar (com.github.yalantis:ucrop:2.2.8)
  Duplicate class com.yalantis.ucrop.UCrop$Options found in modules jetified-pictureselector-v2.7.3-rc10-runtime.jar (io.github.lucksiege:pictureselector:v2.7.3-rc10) and jetified-ucrop-2.2.8-runtime.jar (com.github.yalantis:ucrop:2.2.8)
  Duplicate class com.yalantis.ucrop.UCropActivity found in modules jetified-pictureselector-v2.7.3-rc10-runtime.jar (io.github.lucksiege:pictureselector:v2.7.3-rc10) and jetified-ucrop-2.2.8-runtime.jar (com.github.yalantis:ucrop:2.2.8)
  Duplicate class com.yalantis.ucrop.UCropActivity$1 found in modules jetified-pictureselector-v2.7.3-rc10-runtime.jar (io.github.lucksiege:pictureselector:v2.7.3-rc10) and jetified-ucrop-2.2.8-runtime.jar (com.github.yalantis:ucrop:2.2.8)
  Duplicate class com.yalantis.ucrop.UCropActivity$2 found in modules jetified-pictureselector-v2.7.3-rc10-runtime.jar (io.github.lucksiege:pictureselector:v2.7.3-rc10) and jetified-ucrop-2.2.8-runtime.jar (com.github.yalantis:ucrop:2.2.8)
  Duplicate class com.yalantis.ucrop.UCropActivity$3 found in modules jetified-pictureselector-v2.7.3-rc10-runtime.jar (io.github.lucksiege:pictureselector:v2.7.3-rc10) and jetified-ucrop-2.2.8-runtime.jar (com.github.yalantis:ucrop:2.2.8)
  Duplicate class com.yalantis.ucrop.UCropActivity$4 found in modules jetified-pictureselector-v2.7.3-rc10-runtime.jar (io.github.lucksiege:pictureselector:v2.7.3-rc10) and jetified-ucrop-2.2.8-runtime.jar (com.github.yalantis:ucrop:2.2.8)
  Duplicate class com.yalantis.ucrop.UCropActivity$5 found in modules jetified-pictureselector-v2.7.3-rc10-runtime.jar (io.github.lucksiege:pictureselector:v2.7.3-rc10) and jetified-ucrop-2.2.8-runtime.jar (com.github.yalantis:ucrop:2.2.8)
  Duplicate class com.yalantis.ucrop.UCropActivity$6 found in modules jetified-pictureselector-v2.7.3-rc10-runtime.jar (io.github.lucksiege:pictureselector:v2.7.3-rc10) and jetified-ucrop-2.2.8-runtime.jar (com.github.yalantis:ucrop:2.2.8)
  Duplicate class com.yalantis.ucrop.UCropActivity$7 found in modules jetified-pictureselector-v2.7.3-rc10-runtime.jar (io.github.lucksiege:pictureselector:v2.7.3-rc10) and jetified-ucrop-2.2.8-runtime.jar (com.github.yalantis:ucrop:2.2.8)
  Duplicate class com.yalantis.ucrop.UCropActivity$8 found in modules jetified-pictureselector-v2.7.3-rc10-runtime.jar (io.github.lucksiege:pictureselector:v2.7.3-rc10) and jetified-ucrop-2.2.8-runtime.jar (com.github.yalantis:ucrop:2.2.8)
  Duplicate class com.yalantis.ucrop.UCropActivity$GestureTypes found in modules jetified-pictureselector-v2.7.3-rc10-runtime.jar (io.github.lucksiege:pictureselector:v2.7.3-rc10) and jetified-ucrop-2.2.8-runtime.jar (com.github.yalantis:ucrop:2.2.8)
  Duplicate class com.yalantis.ucrop.callback.BitmapCropCallback found in modules jetified-pictureselector-v2.7.3-rc10-runtime.jar (io.github.lucksiege:pictureselector:v2.7.3-rc10) and jetified-ucrop-2.2.8-runtime.jar (com.github.yalantis:ucrop:2.2.8)
  Duplicate class com.yalantis.ucrop.callback.BitmapLoadCallback found in modules jetified-pictureselector-v2.7.3-rc10-runtime.jar (io.github.lucksiege:pictureselector:v2.7.3-rc10) and jetified-ucrop-2.2.8-runtime.jar (com.github.yalantis:ucrop:2.2.8)
  Duplicate class com.yalantis.ucrop.callback.CropBoundsChangeListener found in modules jetified-pictureselector-v2.7.3-rc10-runtime.jar (io.github.lucksiege:pictureselector:v2.7.3-rc10) and jetified-ucrop-2.2.8-runtime.jar (com.github.yalantis:ucrop:2.2.8)
 Duplicate class com.yalantis.ucrop.view.TransformImageView found in modules jetified-pictureselector-v2.7.3-rc10-runtime.jar (io.github.lucksiege:pictureselector:v2.7.3-rc10) and jetified-ucrop-2.2.8-runtime.jar (com.github.yalantis:ucrop:2.2.8)
  Duplicate class com.yalantis.ucrop.view.TransformImageView$1 found in modules jetified-pictureselector-v2.7.3-rc10-runtime.jar (io.github.lucksiege:pictureselector:v2.7.3-rc10) and jetified-ucrop-2.2.8-runtime.jar (com.github.yalantis:ucrop:2.2.8)
  Duplicate class com.yalantis.ucrop.view.TransformImageView$TransformImageListener found in modules jetified-pictureselector-v2.7.3-rc10-runtime.jar (io.github.lucksiege:pictureselector:v2.7.3-rc10) and jetified-ucrop-2.2.8-runtime.jar (com.github.yalantis:ucrop:2.2.8)
  Duplicate class com.yalantis.ucrop.view.UCropView found in modules jetified-pictureselector-v2.7.3-rc10-runtime.jar (io.github.lucksiege:pictureselector:v2.7.3-rc10) and jetified-ucrop-2.2.8-runtime.jar (com.github.yalantis:ucrop:2.2.8)
  Duplicate class com.yalantis.ucrop.view.UCropView$1 found in modules jetified-pictureselector-v2.7.3-rc10-runtime.jar (io.github.lucksiege:pictureselector:v2.7.3-rc10) and jetified-ucrop-2.2.8-runtime.jar (com.github.yalantis:ucrop:2.2.8)
  Duplicate class com.yalantis.ucrop.view.UCropView$2 found in modules jetified-pictureselector-v2.7.3-rc10-runtime.jar (io.github.lucksiege:pictureselector:v2.7.3-rc10) and jetified-ucrop-2.2.8-runtime.jar (com.github.yalantis:ucrop:2.2.8)
  Duplicate class com.yalantis.ucrop.view.widget.AspectRatioTextView found in modules jetified-pictureselector-v2.7.3-rc10-runtime.jar (io.github.lucksiege:pictureselector:v2.7.3-rc10) and jetified-ucrop-2.2.8-runtime.jar (com.github.yalantis:ucrop:2.2.8)
  Duplicate class com.yalantis.ucrop.view.widget.HorizontalProgressWheelView found in modules jetified-pictureselector-v2.7.3-rc10-runtime.jar (io.github.lucksiege:pictureselector:v2.7.3-rc10) and jetified-ucrop-2.2.8-runtime.jar (com.github.yalantis:ucrop:2.2.8)
  Duplicate class com.yalantis.ucrop.view.widget.HorizontalProgressWheelView$ScrollingListener found in modules jetified-pictureselector-v2.7.3-rc10-runtime.jar (io.github.lucksiege:pictureselector:v2.7.3-rc10) and jetified-ucrop-2.2.8-runtime.jar (com.github.yalantis:ucrop:2.2.8)

  Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.

**Comment by hnvn** [comment]
You are using a package that depends on [this library](https://github.com/LuckSiege/PictureSelector). In the source of `PictuerSelector` includes a clone of `uCrop` repo (the library that `image_cropper` depends on). That's why causes duplicate issue. There's no option to adopt of both libraries here, you have select one `image_copper` package or the other package. Thanks for your feedback.
