### ISSUE TITLE
Override bottom colors

### ISSUE THREAD

**Issue by pablote** [hnvn/flutter_image_cropper#37]
I've just recently upgraded to v1.0.1 and the Android view seems to have adopted some new colors. I was able to customize the top toolbar colors, but I haven't been able the change the bottom section, which is now purple. Does the underlying Android component allow overriding this color? thanks!

<img width="369" alt="Screen Shot 2019-04-17 at 6 30 04 PM" src="https://user-images.githubusercontent.com/2463995/56322360-3f0a8a00-613f-11e9-89b5-924650a19560.png">

**Comment by hnvn** [comment]
I am also finding a way to do this, it seems that the native library doesn't support it. I will try to make an issue for it in the native library repository

**Comment by hnvn** [comment]
This might be a solution: https://github.com/Yalantis/uCrop/issues/161#issuecomment-245605547

**Comment by juliengit2** [comment]
It could be really nice if we can override also the bottom colors.

**Comment by hnvn** [comment]
That solution doesn't work, does it?

**Comment by juliengit2** [comment]
seems it's needed to override colors in color.xml, where is this file located? we don't have any file like this in our flutter project..

**Comment by hnvn** [comment]
That's right, it's in the scope of Android native codes. You can go to `android` folder and create `color.xml` file under folder `app/src/main/res/values`. That's all I can support in this case because this plugin depends on native libraries and if doesn't expose an API to customize that color, I can do nothing from Dart side.

**Comment by hnvn** [comment]
The content of `color.xml` might look like:
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="ucrop_color_widget_background">#ffff5722</color> <!-- update the color you want -->
</resources>
```

**Comment by juliengit2** [comment]
thank you, it works for the bottom colors, any idea about to change the 3 texts at the bottom (rotate, crop, scale) ?

**Comment by juliengit2** [comment]
I added those ressources in /app/src/main/res/values/strings.xml:

<string name="ucrop_rotate">Rotate</string>
<string name="ucrop_scale">Scale</string>
<string name="ucrop_crop">Crop</string>

**Comment by hnvn** [comment]
I see you can customize your UI now but in a not convenient way, so we should leave this issue open until I can find a way to support it from Dart codes

**Comment by dvasea1** [comment]
this is not complete solution. Try this:
<?xml version="1.0" encoding="utf-8"?>
<resources xmlns:tools="http://schemas.android.com/tools">
    <color **tools:override="true"** name="ucrop_color_widget_background">#4CAF50</color> 

</resources>

**Comment by FilipeOS** [comment]
Is there any simple solution for the bottom colors already?

@dvasea1 that code is placed in the theme.dart?

**Comment by himanshu096** [comment]
@FilipeOS @dvasea1 have a look at this PR....you can control bottom bar style using the updated library for android. [https://github.com/hnvn/flutter_image_cropper/pull/48#issuecomment-514414719](url)

**Comment by FilipeOS** [comment]
@himanshu096 that url is invalid, can you please recheck?

**Comment by hnvn** [comment]
Try v1.1.0 for better UI customization
