### ISSUE TITLE
Override bottom colors + texts at the bottom

### ISSUE THREAD

**Issue by juliengit2** [hnvn/flutter_image_cropper#38]
The violet color at the bottom cannot be changed, nor the 3 texts at the bottom ("crop", "rotate", "scale")

**Comment by juliengit2** [comment]
I found the solution: 

I added those ressources in /app/src/main/res/values/ strings.xml:

    <string name="ucrop_rotate">Rotate</string>
    <string name="ucrop_scale">Scale</string>
    <string name="ucrop_crop">Crop</string>

**Comment by hnvn** [comment]
Duplication of #37

**Comment by WinterSkipper** [comment]
add android/app/src/main/res/values/colors.xml   file,  and add  【<color name="ucrop_color_widget_background">#D81B60</color>】， bottom color be changed;

**Comment by hnvn** [comment]
Try new v1.1.0 for better UI customization.
