### ISSUE TITLE
jcenter to mavenCentral

### ISSUE THREAD

**Issue by vasilich6107** [hnvn/flutter_image_cropper#380]
Please migrate jCenter to mavenCentral
https://github.com/hnvn/flutter_image_cropper/blob/master/image_cropper/android/build.gradle#L7

`jcenter has been unreliable...`
https://github.com/flutter/flutter/issues/82847

**Comment by hnvn** [comment]
The PR is merged, I close this issue.

**Comment by hnvn** [comment]
it is already released few weeks ago
