### ISSUE TITLE
Bad quality After cropImage method

### ISSUE THREAD

**Issue by hiromumachi** [hnvn/flutter_image_cropper#405]
I am cropping to 240*240 using cropimage.
But after cropImage imagequality is very bad.(image has juggy)
I already set compressQuality: 100.
Do you have any suggestions for improvement?

```
final croppedFile = await ImageCropper().cropImage(
        sourcePath: widget.selectedImames![index].path.toString(),
        compressFormat: extension == "png"
            ? ImageCompressFormat.png
            : ImageCompressFormat.jpg,
        compressQuality: 100,
        maxHeight: 240,
        maxWidth: 240,
        uiSettings: [
          AndroidUiSettings(
              toolbarTitle: 'Cropper',
              toolbarColor: Colors.deepOrange,
              toolbarWidgetColor: Colors.white,
              initAspectRatio: CropAspectRatioPreset.square,
              lockAspectRatio: true,
              hideBottomControls: true)
```

### originalimage
![original](https://user-images.githubusercontent.com/98738535/226177774-e9295878-df5f-4846-9319-e442a05bd970.jpg)

**screenshot**
width 1920 height 1280
<img src="https://user-images.githubusercontent.com/98738535/226177434-31586d9d-cf8c-4b37-93b7-d9f6eb25ae32.jpg" width = "220px" height = "420px">
↓
width 240 height 240
<img src="https://user-images.githubusercontent.com/98738535/226177518-4676c9b8-ad5c-4eaf-8150-44576d7fcce5.jpg" width = "220px" height = "420px">

↓

**Comment by BROUDING** [comment]
Great picture!
It is actually very simple and clear.
This library makes your image into 240x240 size and YOU're trying to display the image as same size as when the image was 1920x1280, that's why.

Let's say the "ImageView" you got on your device has 1000x1000 pixels,
The last screenshot that we're looking at is 240x240 image, so it's stretched about 5 times- compared to the original one you had.

**Comment by hiromumachi** [comment]
thank you BROUDING!
I could solved this issue.
I tried crop Image only one time(maxSize is 240).
that's why this issue occured.
So I changed my code like this.(maxSize is 1000).
First myimage crop 1000*1000 (maxSize) and then copyResize that from Image Class to 240*240.

```
final croppedFile = await ImageCropper().cropImage(
        sourcePath: widget.selectedImames![index].path.toString(),
        compressFormat: extension == "png"
            ? ImageCompressFormat.png
            : ImageCompressFormat.jpg,
        compressQuality: 100,
        maxHeight: 1000,
        maxWidth: 1000,
        uiSettings: [
          AndroidUiSettings(
              toolbarTitle: 'Cropper',
              toolbarColor: Colors.deepOrange,
              toolbarWidgetColor: Colors.white,
              initAspectRatio: CropAspectRatioPreset.square,
              lockAspectRatio: true,
              hideBottomControls: true),
        ],
      );
      if (croppedFile != null) {
        final decodeImage =
            imgclass.decodeImage(await croppedFile.readAsBytes());
        final resizedImage = imgclass.copyResize(decodeImage!,
            width: 240,
            height: 240,
            interpolation: imgclass.Interpolation.average);
```


Your explanation [it's stretched about 5 times] is what I wanted!
SO thank you a lot!
