### ISSUE TITLE
Compile error after installing plugin

### ISSUE THREAD

**Issue by OmgKevin** [hnvn/flutter_image_cropper#41]
I installed your plugin in .yaml and submitted it to the git management repository. When my colleague pulled the new project, the first time I compiled the error, the error message:

/////////////////*******/////////////////
KevinOmg:blingabc_student_app xingkunkun$ flutter run
Launching lib/main.dart on iPhone 7 Plus in debug mode...

Compiler message:
file:///Users/xingkunkun/.pub-cache/hosted/pub.flutter-io.cn/orientation-1.0.4/lib/orientation.dart:17:28: Error:
Expected 0 type arguments.
      await _methodChannel.invokeMethod<void>(
                           ^
file:///Users/xingkunkun/.pub-cache/hosted/pub.flutter-io.cn/orientation-1.0.4/lib/orientation.dart:28:26: Error:
Expected 0 type arguments.
    await _methodChannel.invokeMethod<void>(
                         ^
file:///Users/xingkunkun/.pub-cache/hosted/pub.flutter-io.cn/orientation-1.0.4/lib/orientation.dart:35:26: Error:
Expected 0 type arguments.
    await _methodChannel.invokeMethod<void>(
                         ^
Compiler failed on /Users/xingkunkun/Desktop/BBB/blingabc_student_app/lib/main.dart
Error launching application on iPhone 7 Plus.
/////////////////*******/////////////////
But when trying to run again, the error no longer exists, and everything is ok, can you tell me why?

**Comment by hnvn** [comment]
Why I think this error comes from `image_cropper`, I have no idea about `orientation-1.0.4` showed in your error log.

**Comment by OmgKevin** [comment]
I don't understand this error very well. The version uses 1.0.1, the IDE is VSCode, and the first execution will give an error.

**Comment by OmgKevin** [comment]
I am wondering if it conflicts with other plugins. According to my understanding, I use it with image_picker 0.5.2 and it will not cause conflicts.
