### ISSUE TITLE
Namespace not specified. Android.

### ISSUE THREAD

**Issue by RedFox64** [hnvn/flutter_image_cropper#419]
I changed gradle-7.6 to gradle-8.1

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':image_cropper'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Please specify a namespace in the module's build.gradle file like so:

     android {
         namespace 'com.example.namespace'
     }

     If the package attribute is specified in the source AndroidManifest.xml, it can be migrated automatically to the namespace value in the build.gradle file using the AGP Upgrade Assistant; please refer to https://developer.android.com/studio/build/agp-upgrade-assistant for more information.

**Comment by hnvn** [comment]
fixed in v4.0.0
