### ISSUE TITLE
please support androidx

### ISSUE THREAD

**Issue by jiaxa** [hnvn/flutter_image_cropper#42]
this's so good to use,
but it not support androidx,
please support androidx,thanks
😊

**Comment by hnvn** [comment]
It has been migrated to AndroidX

**Comment by jiaxa** [comment]
when I use it:

`I/zygote64(26040): Rejecting re-init on previously-failed class java.lang.Class<com.yalantis.ucrop.UCropActivity>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v7/app/AppCompatActivity;
I/zygote64(26040):   at android.content.Intent com.yalantis.ucrop.UCrop.getIntent(android.content.Context) (UCrop.java:186)
I/zygote64(26040):   at void com.yalantis.ucrop.UCrop.start(android.app.Activity, int) (UCrop.java:138)
I/zygote64(26040):   at void com.yalantis.ucrop.UCrop.start(android.app.Activity) (UCrop.java:128)
I/zygote64(26040):   at void vn.hunghd.flutter.plugins.imagecropper.ImageCropperDelegate.startCrop(io.flutter.plugin.common.MethodCall, io.flutter.plugin.common.MethodChannel$Result) (ImageCropperDelegate.java:91)
I/zygote64(26040):   at void vn.hunghd.flutter.plugins.imagecropper.ImageCropperPlugin.onMethodCall(io.flutter.plugin.common.MethodCall, io.flutter.plugin.common.MethodChannel$Result) (ImageCropperPlugin.java:36)
I/zygote64(26040):   at void io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(java.nio.ByteBuffer, io.flutter.plugin.common.BinaryMessenger$BinaryReply) (MethodChannel.java:201)
I/zygote64(26040):   at void io.flutter.view.FlutterNativeView$PlatformMessageHandlerImpl.handleMessageFromDart(java.lang.String, byte[], int) (FlutterNativeView.java:188)
I/zygote64(26040):   at void io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(java.lang.String, byte[], int) (FlutterJNI.java:202)
I/zygote64(26040):   at void android.os.MessageQueue.nativePollOnce(long, int) (MessageQueue.java:-2)
I/zygote64(26040):   at android.os.Message android.os.MessageQueue.next() (MessageQueue.java:332)
I/zygote64(26040):   at void android.os.Looper.loop() (Looper.java:150)
I/zygote64(26040):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6847)
I/zygote64(26040):   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/zygote64(26040):   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:438)
I/zygote64(26040):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:825)
I/zygote64(26040): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v7.app.AppCompatActivity" on path: DexPathList[[zip file "/data/app/com.example.frdffg.frdffg-3NDxFHPxTdi5xVS-DM5K9w==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.frdffg.frdffg-3NDxFHPxTdi5xVS-DM5K9w==/lib/arm64, /data/app/com.example.frdffg.frdffg-3NDxFHPxTdi5xVS-DM5K9w==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
I/zygote64(26040):   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:125)
I/zygote64(26040):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
I/zygote64(26040):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/zygote64(26040):   at android.content.Intent com.yalantis.ucrop.UCrop.getIntent(android.content.Context) (UCrop.java:186)
I/zygote64(26040):   at void com.yalantis.ucrop.UCrop.start(android.app.Activity, int) (UCrop.java:138)
I/zygote64(26040):   at void com.yalantis.ucrop.UCrop.start(android.app.Activity) (UCrop.java:128)
I/zygote64(26040):   at void vn.hunghd.flutter.plugins.imagecropper.ImageCropperDelegate.startCrop(io.flutter.plugin.common.MethodCall, io.flutter.plugin.common.MethodChannel$Result) (ImageCropperDelegate.java:91)
I/zygote64(26040):   at void vn.hunghd.flutter.plugins.imagecropper.ImageCropperPlugin.onMethodCall(io.flutter.plugin.common.MethodCall, io.flutter.plugin.common.MethodChannel$Result) (ImageCropperPlugin.java:36)
I/zygote64(26040):   at void io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(java.nio.ByteBuffer, io.flutter.plugin.common.BinaryMessenger$BinaryReply) (MethodChannel.java:201)
I/zygote64(26040):   at void io.flutter.view.FlutterNativeView$PlatformMessageHandlerImpl.handleMessageFromDart(java.lang.String, byte[], int) (FlutterNativeView.java:188)
I/zygote64(26040):   at void io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(java.lang.String, byte[], int) (FlutterJNI.java:202)
I/zygote64(26040):   at void android.os.MessageQueue.nativePollOnce(long, int) (MessageQueue.java:-2)
I/zygote64(26040):   at android.os.Message android.os.MessageQueue.next() (MessageQueue.java:332)
I/zygote64(26040):   at void android.os.Looper.loop() (Looper.java:150)
I/zygote64(26040):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6847)
I/zygote64(26040):   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/zygote64(26040):   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:438)
I/zygote64(26040):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:825)
I/zygote64(26040): 
E/flutter (26040): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(40)] java.lang.NoClassDefFoundError: Failed resolution of: Lcom/yalantis/ucrop/UCropActivity;
E/flutter (26040): 	at com.yalantis.ucrop.UCrop.getIntent(UCrop.java:186)
E/flutter (26040): 	at com.yalantis.ucrop.UCrop.start(UCrop.java:138)
E/flutter (26040): 	at com.yalantis.ucrop.UCrop.start(UCrop.java:128)
E/flutter (26040): 	at vn.hunghd.flutter.plugins.imagecropper.ImageCropperDelegate.startCrop(ImageCropperDelegate.java:91)
E/flutter (26040): 	at vn.hunghd.flutter.plugins.imagecropper.ImageCropperPlugin.onMethodCall(ImageCropperPlugin.java:36)
E/flutter (26040): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
E/flutter (26040): 	at io.flutter.view.FlutterNativeView$PlatformMessageHandlerImpl.handleMessageFromDart(FlutterNativeView.java:188)
E/flutter (26040): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:202)
E/flutter (26040): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (26040): 	at android.os.MessageQueue.next(MessageQueue.java:332)
E/flutter (26040): 	at android.os.Looper.loop(Looper.java:150)
E/flutter (26040): 	at android.app.ActivityThread.main(ActivityThread.java:6847)
E/flutter (26040): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (26040): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/flutter (26040): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:825)
E/flutter (26040): Caused by: java.lang.ClassNotFoundException: com.yalantis.ucrop.UCropActivity
E/flutter (26040): 	at java.lang.VMClassLoader.findLoadedClass(Native Method)
E/flutter (26040): 	at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
E/flutter (26040): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
E/flutter (26040): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/flutter (26040): 	... 15 more
E/flutter (26040): Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v7/app/AppCompatActivity;
E/flutter (26040): 	... 15 more
E/flutter (26040): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v7.app.AppCompatActivity" on path: DexPathList[[zip file "/data/app/com.example.frdffg.frdffg-3NDxFHPxTdi5xVS-DM5K9w==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.frdffg.frdffg-3NDxFHPxTdi5xVS-DM5K9w==/lib/arm64, /data/app/com.example.frdffg.frdffg-3NDxFHPxTdi5xVS-DM5K9w==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
E/flutter (26040): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
E/flutter (26040): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/flutter (26040): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/flutter (26040): 	... 15 more
E/flutter (26040): 
F/flutter (26040): [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(77)] Check failed: CheckException(env). 
F/libc    (26040): Fatal signal 6 (SIGABRT), code -6 in tid 26040 (e.frdffg.frdffg), pid 26040 (e.frdffg.frdffg)`

please help me,I'm not a real android developer

**Comment by hnvn** [comment]
This plugin is full support AndroidX, your issue seems to a problem with project configuration and gradle version.
