### ISSUE TITLE
Update the http package to version 1.0.0

### ISSUE THREAD

**Issue by rahmanrezaee** [hnvn/flutter_image_cropper#424]
First of all, I appreciate you and all contributors for your hard work and build such an amazing plugin.

![image](https://github.com/hnvn/flutter_image_cropper/assets/37028113/2de60968-3cbc-4935-9122-fc13fdda015b)

I'm using the last version of [`Google Font Package`](https://pub.dev/packages/google_fonts) and its need http 1.0.0 and your package depends to older version (http ^0.13.4)

**Comment by ewankirk** [comment]
It would be good if this could be updated and pushed.  I'd like to use the latest Google Font package as well.

**Comment by Silverviql** [comment]
I'm using the last version of [flutter_map](https://pub.dev/packages/flutter_map) and  and its need http 1.0.0 and your package depends to older version (http ^0.13.4)

**Comment by Gaurav-CareMonitor** [comment]
+1

**Comment by hnvn** [comment]
The last version v5.0.0 already used http v1.0.0 https://github.com/hnvn/flutter_image_cropper/blob/master/image_cropper_platform_interface/pubspec.yaml#L14
