### ISSUE TITLE
Support for other languages

### ISSUE THREAD

**Issue by rafaeldalbosco** [hnvn/flutter_image_cropper#43]
Hello I found the package interesting and I would like to know how to use other languages direct from English.

**Comment by shinayser** [comment]
+1 on this issue. Right now the plugin only offers English.

**Comment by shinayser** [comment]
I found a easy sollution for that:

There are 6 strings you can translate if you wish/want.
Just add these lines to your own projects app/src/main/res/values=> strings.xml
```
<string name="ucrop_label_original">Original</string>
<string name="ucrop_label_edit_photo">Edit Photo</string>
<string name="ucrop_menu_next">Next</string>
<string name="ucrop_rotate">Rotate</string>
<string name="ucrop_scale">Scale</string>
<string name="ucrop_crop">Crop</string>
```
and translate whatever language you need.

**Comment by hnvn** [comment]
#37
