### ISSUE TITLE
How to crop uint8list?

### ISSUE THREAD

**Issue by NedoPrograMax** [hnvn/flutter_image_cropper#435]
Is there a way to crop image when you don't have a file? I ask because I'm using flutter web, and so I can't just convert bytes to file and then use the new path :)

**Comment by mauriziopinotti** [comment]
I ended up using the `cross_file` plugin and converting the picked image to an XFile before passing it to `ImageCropper`:

```dart
    // Pick image
    final pickedImage = await showFilePicker(FileType.image);
    if (pickedImage == null) return;

    // Convert to XFile
    final file = XFile.fromData(pickedImage.bytes!);

    // Now you can use file.path on all platforms
    final croppedFile =
        await ImageCropper().cropImage(sourcePath: file.path, uiSettings: [
```

**Comment by NedoPrograMax** [comment]
Thank you for your code, it works perfectly😀
