### ISSUE TITLE
crop result left on ios device aap data folder 

### ISSUE THREAD

**Issue by keitoro** [hnvn/flutter_image_cropper#45]
It seems that the cropper leaves an image in the data directory of the app and is slowly increasing the app size. I notice that it only happens when I use the cropper which is odd. 

I have no idea how to remove this file or data. I have tried clearing that folder, I can remove the cropped image but there is still 1 MB left of something. I have no idea what it is and how to delete it. 

Any ideas when this could be and how to solve this?

**Comment by hnvn** [comment]
This plugin needs to create a new file for cropped result, I save it at app data folder where the application doesn't need more permission to access. If you want to delete these files, you can try to delete them implicitly in your Dart code, I haven't tried yet, but I guess it looks like:
```
croppedImageFile.delete();
```
