### ISSUE TITLE
Add property to hide bottom controls (com.yalantis.ucrop.HideBottomControls)

### ISSUE THREAD

**Issue by SebastianEngel** [hnvn/flutter_image_cropper#47]
It would be great to be able to hide the bottom controls. 

I had a look into UCropActivity and found out that this is supported by UCrop with the Intent Extra called `com.yalantis.ucrop.HideBottomControls`. There should be an additional optional parameter in `ImageCropper.cropImage()` which allows exactly this.

**Comment by hnvn** [comment]
supported now in v1.1.0
