### ISSUE TITLE
Version ^6.0.0

### ISSUE THREAD

**Issue by gujjar1988** [hnvn/flutter_image_cropper#486]
**When we are going for image_cropper: ^6.0.0
Then I got below installing error.
You please update it.**

_Resolving dependencies..._
Because image_cropper >=6.0.0 depends on image_cropper_for_web ^4.0.0 which depends on js ^0.7.1, image_cropper >=6.0.0 requires js ^0.7.1.
And because flutter_secure_storage_web 1.2.1 depends on js ^0.6.3 and no versions of flutter_secure_storage_web match >1.2.1 <2.0.0, image_cropper >=6.0.0 is incompatible with flutter_secure_storage_web ^1.2.1.
And because flutter_secure_storage 9.1.1 depends on flutter_secure_storage_web ^1.2.1 and no versions of flutter_secure_storage match >9.1.1 <10.0.0, image_cropper >=6.0.0 is incompatible with flutter_secure_storage ^9.1.1.
So, because sds depends on both flutter_secure_storage ^9.1.1 and image_cropper ^6.0.0, version solving failed.

**Comment by hnvn** [comment]
then, you have to either override the js version to 0.7.1 or downgrade the `image_cropper` to use version 5.x.x
