### ISSUE TITLE
image_cropper >=6.0.0 is incompatible with flutter_secure_storage_web ^1.2.1.

### ISSUE THREAD

**Issue by bugrevealingbme** [hnvn/flutter_image_cropper#488]
Because image_cropper >=6.0.0 depends on image_cropper_for_web ^4.0.0 which depends on js ^0.7.1, image_cropper >=6.0.0 requires js ^0.7.1.
Because flutter_secure_storage_web 1.2.1 depends on js ^0.6.3 and no versions of flutter_secure_storage_web match >1.2.1 <2.0.0, flutter_secure_storage_web ^1.2.1 requires js ^0.6.3.
Thus, image_cropper >=6.0.0 is incompatible with flutter_secure_storage_web ^1.2.1.
And because flutter_secure_storage 9.1.1 depends on flutter_secure_storage_web ^1.2.1 and no versions of flutter_secure_storage match >9.1.1 <10.0.0, image_cropper >=6.0.0 is incompatible with flutter_secure_storage ^9.1.1.

**Comment by bugrevealingbme** [comment]
I just downgraded

**Comment by hnvn** [comment]
duplicated of #486

**Comment by gujjar1988** [comment]
> Because image_cropper >=6.0.0 depends on image_cropper_for_web ^4.0.0 which depends on js ^0.7.1, image_cropper >=6.0.0 requires js ^0.7.1. Because flutter_secure_storage_web 1.2.1 depends on js ^0.6.3 and no versions of flutter_secure_storage_web match >1.2.1 <2.0.0, flutter_secure_storage_web ^1.2.1 requires js ^0.6.3. Thus, image_cropper >=6.0.0 is incompatible with flutter_secure_storage_web ^1.2.1. And because flutter_secure_storage 9.1.1 depends on flutter_secure_storage_web ^1.2.1 and no versions of flutter_secure_storage match >9.1.1 <10.0.0, image_cropper >=6.0.0 is incompatible with flutter_secure_storage ^9.1.1.

same with me
