### ISSUE TITLE
Wasm Support

### ISSUE THREAD

**Issue by ps6067966** [hnvn/flutter_image_cropper#490]
It will be great if this package support WASM

**Comment by OlegShNayax** [comment]
Any updates?

**Comment by hnvn** [comment]
I will work on it when I am available, but I am not much experience in Web development, so it would take more time for me to work on it. It is much appreciated if there's any helps from community

**Comment by GenildoNogueira** [comment]
Hello hnvn,

I hope you're doing well. I wanted to share an update regarding the Wasm compilation issue.

After some investigation and testing, I managed to compile it correctly for Wasm.

However, I'm facing this issue:
`TypeError: dart.global.Croppie is not a constructor
packages/image_cropper_for_web/src/croppie/croppie_dart.dart 129:50               new
packages/image_cropper_for_web/src/croppie/croppie_dart.dart 68:12                new
packages/image_cropper_for_web/image_cropper_for_web.dart 128:21                  cropImage
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 127:5                _async
packages/image_cropper_for_web/image_cropper_for_web.dart 72:33                   cropImage
packages/image_cropper/src/cropper.dart 84:21                                     cropImage
packages/example/main.dart 315:48                                                 _cropImage
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 127:5                _async
packages/example/main.dart 277:26                                                 [_cropImage]
packages/example/main.dart 208:17                                                 <fn>
packages/flutter/src/material/ink_well.dart 1171:21                               handleTap
packages/flutter/src/gestures/recognizer.dart 344:24                              invokeCallback
packages/flutter/src/gestures/tap.dart 652:11                                     handleTapUp
packages/flutter/src/gestures/tap.dart 309:5                                      [_checkUp]
packages/flutter/src/gestures/tap.dart 242:7                                      handlePrimaryPointer
packages/flutter/src/gestures/recognizer.dart 696:9                               handleEvent
packages/flutter/src/gestures/pointer_router.dart 98:7                            [_dispatch]
packages/flutter/src/gestures/pointer_router.dart 143:9                           <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/linked_hash_map.dart 21:7           forEach
packages/flutter/src/gestures/pointer_router.dart 141:17                          [_dispatchEventToRoutes]
packages/flutter/src/gestures/pointer_router.dart 127:7                           route
packages/flutter/src/gestures/binding.dart 495:5                                  handleEvent
packages/flutter/src/gestures/binding.dart 475:14                                 dispatchEvent
packages/flutter/src/rendering/binding.dart 425:11                                dispatchEvent
packages/flutter/src/gestures/binding.dart 420:7                                  [_handlePointerEventImmediately]
packages/flutter/src/gestures/binding.dart 383:5                                  handlePointerEvent
packages/flutter/src/gestures/binding.dart 330:7                                  [_flushPointerEventQueue]
packages/flutter/src/gestures/binding.dart 299:9                                  [_handlePointerDataPacket]
lib/_engine/engine/platform_dispatcher.dart 1419:5                                invoke1
lib/_engine/engine/platform_dispatcher.dart 333:5                                 invokeOnPointerDataPacket
lib/_engine/engine/pointer_binding.dart 398:30                                    [_sendToFramework]
lib/_engine/engine/pointer_binding.dart 224:7                                     onPointerData
lib/_engine/engine/pointer_binding.dart 1001:20                                   <fn>
lib/_engine/engine/pointer_binding.dart 930:7                                     <fn>
lib/_engine/engine/pointer_binding.dart 531:9                                     loggedHandler
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 426:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 431:39  dcall`

Looking forward to your guidance on how to proceed.

**Comment by hnvn** [comment]
Hi everyone,

I've successfully migrated our plug-in to use the new JS library, Cropper.js, instead of Croppie. This change addresses many existing issues on the web platform, including support for WebAssembly (Wasm).

Please take some time to test the plug-in and help identify and fix any breaking features (I have not released new version yet, so please get the new codes directly from github). Your assistance is greatly appreciated.

Thank you!

**Comment by GenildoNogueira** [comment]
Awesome work on migrating to Cropper.js! I'm excited to test it out and see the improvements.

**Comment by hnvn** [comment]
Released new version v7.0.0
