### ISSUE TITLE
CHANGELOG references nonexistent AndroidUiSettings.title

### ISSUE THREAD

**Issue by zmuranaka** [hnvn/flutter_image_cropper#495]
The migration guide for version 7.0.0 references `AndroidUiSettings.title` which does not exist. See [here](https://github.com/hnvn/flutter_image_cropper/blob/master/image_cropper/CHANGELOG.md?plain=1#L28) and [here](https://github.com/hnvn/flutter_image_cropper/blob/master/image_cropper/CHANGELOG.md?plain=1#L43).

I believe it is supposed to say `toolbarTitle` instead of `title`.

**Comment by hnvn** [comment]
oops, that's my typo

**Comment by zmuranaka** [comment]
Resolved by 6b690052276d902af4dd006f90581020ecae9423
