### ISSUE TITLE
Build Failed On Flutter Web  The method 'UnmodifiableUint8ListView' isn't defined for the class 'CroppedFile'.( Amazon Code Pipeline)

### ISSUE THREAD

**Issue by Aslamabdulla** [hnvn/flutter_image_cropper#505]
<head></head>
[Container] 2024/06/27 06:41:41.300340 Running on CodeBuild On-demand
--
[Container] 2024/06/27 06:41:41.300353 Waiting for agent ping
[Container] 2024/06/27 06:41:41.401658 Waiting for DOWNLOAD_SOURCE
[Container] 2024/06/27 06:41:42.718016 Phase is DOWNLOAD_SOURCE
[Container] 2024/06/27 06:41:42.733900 CODEBUILD_SRC_DIR=/codebuild/output/src1485100722/src
[Container] 2024/06/27 06:41:42.734396 YAML location is /codebuild/readonly/buildspec.yml
[Container] 2024/06/27 06:41:42.736256 Setting HTTP client timeout to higher timeout for S3 source
[Container] 2024/06/27 06:41:42.736368 Processing environment variables
[Container] 2024/06/27 06:41:42.944899 Selecting 'java' runtime version 'corretto17' based on manual selections...
[Container] 2024/06/27 06:41:42.945699 Running command echo "Installing Corretto(OpenJDK) version 17 ..."
Installing Corretto(OpenJDK) version 17 ...
 
[Container] 2024/06/27 06:41:43.007345 Running command export JAVA_HOME="$JAVA_17_HOME"
 
[Container] 2024/06/27 06:41:43.011653 Running command export JRE_HOME="$JRE_17_HOME"
 
[Container] 2024/06/27 06:41:43.015374 Running command export JDK_HOME="$JDK_17_HOME"
 
[Container] 2024/06/27 06:41:43.018815 Running command for tool_path in "$JAVA_HOME"/bin/*;
do tool=`basename "$tool_path"`;
if [ $tool != 'java-rmi.cgi' ];
then
rm -f /usr/bin/$tool /var/lib/alternatives/$tool;
update-alternatives --install /usr/bin/$tool $tool $tool_path 20000;
update-alternatives --set $tool $tool_path;
fi;
done
update-alternatives: warning: forcing reinstallation of alternative /usr/lib/jvm/java-17-amazon-corretto/bin/jar because link group jar is broken
update-alternatives: warning: forcing reinstallation of alternative /usr/lib/jvm/java-17-amazon-corretto/bin/jarsigner because link group jarsigner is broken
update-alternatives: warning: forcing reinstallation of alternative /usr/lib/jvm/java-17-amazon-corretto/bin/java because link group java is broken
update-alternatives: warning: forcing reinstallation of alternative /usr/lib/jvm/java-17-amazon-corretto/bin/javac because link group javac is broken
update-alternatives: warning: forcing reinstallation of alternative /usr/lib/jvm/java-17-amazon-corretto/bin/javadoc because link group javadoc is broken
update-alternatives: warning: forcing reinstallation of alternative /usr/lib/jvm/java-17-amazon-corretto/bin/javap because link group javap is broken
update-alternatives: warning: forcing reinstallation of alternative /usr/lib/jvm/java-17-amazon-corretto/bin/jcmd because link group jcmd is broken
update-alternatives: warning: forcing reinstallation of alternative /usr/lib/jvm/java-17-amazon-corretto/bin/jconsole because link group jconsole is broken
update-alternatives: warning: forcing reinstallation of alternative /usr/lib/jvm/java-17-amazon-corretto/bin/jdb because link group jdb is broken
update-alternatives: warning: forcing reinstallation of alternative /usr/lib/jvm/java-17-amazon-corretto/bin/jdeprscan because link group jdeprscan is broken
update-alternatives: warning: forcing reinstallation of alternative /usr/lib/jvm/java-17-amazon-corretto/bin/jdeps because link group jdeps is broken
update-alternatives: warning: forcing reinstallation of alternative /usr/lib/jvm/java-17-amazon-corretto/bin/jfr because link group jfr is broken
update-alternatives: warning: forcing reinstallation of alternative /usr/lib/jvm/java-17-amazon-corretto/bin/jhsdb because link group jhsdb is broken
update-alternatives: warning: forcing reinstallation of alternative /usr/lib/jvm/java-17-amazon-corretto/bin/jimage because link group jimage is broken
update-alternatives: warning: forcing reinstallation of alternative /usr/lib/jvm/java-17-amazon-corretto/bin/jinfo because link group jinfo is broken
update-alternatives: warning: forcing reinstallation of alternative /usr/lib/jvm/java-17-amazon-corretto/bin/jlink because link group jlink is broken
update-alternatives: warning: forcing reinstallation of alternative /usr/lib/jvm/java-17-amazon-corretto/bin/jmap because link group jmap is broken
update-alternatives: warning: forcing reinstallation of alternative /usr/lib/jvm/java-17-amazon-corretto/bin/jmod because link group jmod is broken
update-alternatives: warning: forcing reinstallation of alternative /usr/lib/jvm/java-17-amazon-corretto/bin/jpackage because link group jpackage is broken
update-alternatives: warning: forcing reinstallation of alternative /usr/lib/jvm/java-17-amazon-corretto/bin/jps because link group jps is broken
update-alternatives: warning: forcing reinstallation of alternative /usr/lib/jvm/java-17-amazon-corretto/bin/jrunscript because link group jrunscript is broken
update-alternatives: warning: forcing reinstallation of alternative /usr/lib/jvm/java-17-amazon-corretto/bin/jshell because link group jshell is broken
update-alternatives: warning: forcing reinstallation of alternative /usr/lib/jvm/java-17-amazon-corretto/bin/jstack because link group jstack is broken
update-alternatives: warning: forcing reinstallation of alternative /usr/lib/jvm/java-17-amazon-corretto/bin/jstat because link group jstat is broken
update-alternatives: warning: forcing reinstallation of alternative /usr/lib/jvm/java-17-amazon-corretto/bin/jstatd because link group jstatd is broken
update-alternatives: warning: forcing reinstallation of alternative /usr/lib/jvm/java-17-amazon-corretto/bin/keytool because link group keytool is broken
update-alternatives: warning: forcing reinstallation of alternative /usr/lib/jvm/java-17-amazon-corretto/bin/rmiregistry because link group rmiregistry is broken
update-alternatives: warning: forcing reinstallation of alternative /usr/lib/jvm/java-17-amazon-corretto/bin/serialver because link group serialver is broken
 
[Container] 2024/06/27 06:41:44.213533 Moving to directory /codebuild/output/src1485100722/src
[Container] 2024/06/27 06:41:44.215093 Unable to initialize cache download: no paths specified to be cached
[Container] 2024/06/27 06:41:44.305922 Configuring ssm agent with target id: codebuild:868b9b68-13af-4e29-8db9-62778c2cdc36
[Container] 2024/06/27 06:41:44.330012 Successfully updated ssm agent configuration
[Container] 2024/06/27 06:41:44.331724 Registering with agent
[Container] 2024/06/27 06:41:44.364927 Phases found in YAML: 4
[Container] 2024/06/27 06:41:44.364953  INSTALL: 2 commands
[Container] 2024/06/27 06:41:44.364959  PRE_BUILD: 5 commands
[Container] 2024/06/27 06:41:44.364962  BUILD: 4 commands
[Container] 2024/06/27 06:41:44.364966  POST_BUILD: 1 commands
[Container] 2024/06/27 06:41:44.365370 Phase complete: DOWNLOAD_SOURCE State: SUCCEEDED
[Container] 2024/06/27 06:41:44.365392 Phase context status code:  Message:
[Container] 2024/06/27 06:41:44.423420 Entering phase INSTALL
[Container] 2024/06/27 06:41:44.423988 Running command pwd
/codebuild/output/src1485100722/src
 
[Container] 2024/06/27 06:41:44.429798 Running command ls -l
total 788
-rw-rw-r-- 1 root root    550 Jun 27 06:41 README.md
-rw-rw-r-- 1 root root   1484 Jun 27 06:41 analysis_options.yaml
drwxr-xr-x 4 root root    117 Jun 27 06:41 android
drwxr-xr-x 7 root root     73 Jun 27 06:41 assets
-rw-rw-r-- 1 root root     30 Jun 27 06:41 devtools_options.yaml
-rw-rw-r-- 1 root root    137 Jun 27 06:41 firebase.json
-rw-rw-r-- 1 root root  81299 Jun 27 06:41 flutter_01.png
-rw-rw-r-- 1 root root 123908 Jun 27 06:41 flutter_02.png
-rw-rw-r-- 1 root root      0 Jun 27 06:41 flutter_03.png
-rw-rw-r-- 1 root root 319242 Jun 27 06:41 flutter_04.png
-rw-rw-r-- 1 root root 175277 Jun 27 06:41 flutter_05.png
-rw-rw-r-- 1 root root    283 Jun 27 06:41 icon_launcher.yaml
drwxr-xr-x 7 root root    170 Jun 27 06:41 ios
drwxr-xr-x 9 root root    162 Jun 27 06:41 lib
drwxr-xr-x 3 root root    125 Jun 27 06:41 linux
drwxr-xr-x 7 root root    190 Jun 27 06:41 macos
-rw-rw-r-- 1 root root     55 Jun 27 06:41 mason-lock.json
-rw-rw-r-- 1 root root     50 Jun 27 06:41 mason.yaml
-rw-rw-r-- 1 root root  62551 Jun 27 06:41 pubspec.lock
-rw-rw-r-- 1 root root   6203 Jun 27 06:41 pubspec.yaml
drwxr-xr-x 6 root root     88 Jun 27 06:41 test
drwxr-xr-x 3 root root     77 Jun 27 06:41 web
drwxr-xr-x 4 root root     75 Jun 27 06:41 windows
 
[Container] 2024/06/27 06:41:44.464131 Phase complete: INSTALL State: SUCCEEDED
[Container] 2024/06/27 06:41:44.464155 Phase context status code:  Message:
[Container] 2024/06/27 06:41:44.492182 Entering phase PRE_BUILD
[Container] 2024/06/27 06:41:44.492812 Running command echo Pre Build started on `date`
Pre Build started on Thu Jun 27 06:41:44 UTC 2024
 
[Container] 2024/06/27 06:41:44.499736 Running command git clone https://github.com/flutter/flutter.git -b master
Cloning into 'flutter'...
 
[Container] 2024/06/27 06:42:15.104887 Running command export PATH="$PATH:`pwd`/flutter/bin"
 
[Container] 2024/06/27 06:42:15.109774 Running command flutter precache
Downloading Linux x64 Dart SDK from Flutter engine a9194f0f01f42175eaf82a8132167d9c54b60263...
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
 
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
0  203M    0 99706    0     0  81661      0  0:43:30  0:00:01  0:43:29 81659
0  203M    0 1822k    0     0   827k      0  0:04:11  0:00:02  0:04:09  827k
7  203M    7 16.2M    0     0  5180k      0  0:00:40  0:00:03  0:00:37 5178k
16  203M   16 32.9M    0     0  8021k      0  0:00:25  0:00:04  0:00:21 8020k
24  203M   24 49.4M    0     0  9715k      0  0:00:21  0:00:05  0:00:16  9.8M
32  203M   32 66.3M    0     0  10.6M      0  0:00:19  0:00:06  0:00:13 13.2M
39  203M   39 80.8M    0     0  11.2M      0  0:00:18  0:00:07  0:00:11 15.8M
47  203M   47 97.3M    0     0  11.7M      0  0:00:17  0:00:08  0:00:09 16.0M
56  203M   56  114M    0     0  12.3M      0  0:00:16  0:00:09  0:00:07 16.2M
64  203M   64  130M    0     0  12.6M      0  0:00:16  0:00:10  0:00:06 15.8M
71  203M   71  145M    0     0  12.9M      0  0:00:15  0:00:11  0:00:04 15.8M
80  203M   80  163M    0     0  13.2M      0  0:00:15  0:00:12  0:00:03 16.2M
87  203M   87  178M    0     0  13.5M      0  0:00:15  0:00:13  0:00:02 16.4M
95  203M   95  194M    0     0  13.5M      0  0:00:14  0:00:14 --:--:-- 15.7M
100  203M  100  203M    0     0  13.7M      0  0:00:14  0:00:14 --:--:-- 16.2M
Building flutter tool...
Resolving dependencies...
Downloading packages...
Got dependencies.
 
╔════════════════════════════════════════════════════════════════════════════╗
║                 Welcome to Flutter! - https://flutter.dev                  ║
║                                                                            ║
║ The Flutter tool uses Google Analytics to anonymously report feature usage ║
║ statistics and basic crash reports. This data is used to help improve      ║
║ Flutter tools over time.                                                   ║
║                                                                            ║
║ Flutter tool analytics are not sent on the very first run. To disable      ║
║ reporting, type 'flutter config --no-analytics'. To display the current    ║
║ setting, type 'flutter config'. If you opt out of analytics, an opt-out    ║
║ event will be sent, and then no further information will be sent by the    ║
║ Flutter tool.                                                              ║
║                                                                            ║
║ By downloading the Flutter SDK, you agree to the Google Terms of Service.  ║
║ The Google Privacy Policy describes how data is handled in this service.   ║
║                                                                            ║
║ Moreover, Flutter includes the Dart SDK, which may send usage metrics and  ║
║ crash reports to Google.                                                   ║
║                                                                            ║
║ Read about data we send with crash reports:                                ║
║ https://flutter.dev/to/crash-reporting                                     ║
║                                                                            ║
║ See Google's privacy policy:                                               ║
║ https://policies.google.com/privacy                                        ║
║                                                                            ║
║ To disable animations in this tool, use                                    ║
║ 'flutter config --no-cli-animations'.                                      ║
╚════════════════════════════════════════════════════════════════════════════╝
 
Downloading Material fonts...                                      395ms
Downloading Gradle Wrapper...                                        9ms
Downloading android-arm-profile/linux-x64 tools...               1,428ms
Downloading android-arm-release/linux-x64 tools...                 799ms
Downloading android-arm64-profile/linux-x64 tools...               613ms
Downloading android-arm64-release/linux-x64 tools...               740ms
Downloading android-x64-profile/linux-x64 tools...               1,284ms
Downloading android-x64-release/linux-x64 tools...                 335ms
Downloading android-x86 tools...                                    3.0s
Downloading android-x64 tools...                                    3.0s
Downloading android-arm tools...                                 2,827ms
Downloading android-arm-profile tools...                           482ms
Downloading android-arm-release tools...                           413ms
Downloading android-arm64 tools...                               1,688ms
Downloading android-arm64-profile tools...                         500ms
Downloading android-arm64-release tools...                         441ms
Downloading android-x64-profile tools...                           509ms
Downloading android-x64-release tools...                           438ms
Downloading android-x86-jit-release tools...                       567ms
Downloading Web SDK...                                              5.6s
Downloading package sky_engine...                                  313ms
Downloading package flutter_gpu...                                 254ms
Downloading flutter_patched_sdk tools...                           371ms
Downloading flutter_patched_sdk_product tools...                   369ms
Downloading linux-x64 tools...                                      3.7s
Downloading linux-x64-debug/linux-x64-flutter-gtk tools...       2,970ms
Downloading linux-x64-profile/linux-x64-flutter-gtk tools...        564ms
Downloading linux-x64-release/linux-x64-flutter-gtk tools...        532ms
Downloading linux-x64/font-subset tools...                         310ms
 
[Container] 2024/06/27 06:43:40.592270 Running command flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.23.0-13.0.pre.357, on Ubuntu 22.04.4 LTS 4.14.291-218.527.amzn2.x86_64, locale en_US)
[✗] Android toolchain - develop for Android devices
✗ Unable to locate Android SDK.
Install Android Studio from: https://developer.android.com/studio/index.html
On first launch it will assist you in installing the Android SDK components.
(or visit https://flutter.dev/to/linux-android-setup for detailed instructions).
If the Android SDK has been installed to a custom location, please use
`flutter config --android-sdk` to update to that location.
 
[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✗] Linux toolchain - develop for Linux desktop
✗ clang++ is required for Linux development.
It is likely available from your distribution (e.g.: apt install clang), or can be downloaded from https://releases.llvm.org/
✗ CMake is required for Linux development.
It is likely available from your distribution (e.g.: apt install cmake), or can be downloaded from https://cmake.org/download/
✗ ninja is required for Linux development.
It is likely available from your distribution (e.g.: apt install ninja-build), or can be downloaded from https://github.com/ninja-build/ninja/releases
✗ GTK 3.0 development libraries are required for Linux development.
They are likely available from your distribution (e.g.: apt install libgtk-3-dev)
[!] Android Studio (not installed)
[✓] Connected device (1 available)
[✓] Network resources
 
! Doctor found issues in 4 categories.
 
[Container] 2024/06/27 06:43:43.957513 Phase complete: PRE_BUILD State: SUCCEEDED
[Container] 2024/06/27 06:43:43.957538 Phase context status code:  Message:
[Container] 2024/06/27 06:43:43.987637 Entering phase BUILD
[Container] 2024/06/27 06:43:43.988203 Running command echo Build started on `date`
Build started on Thu Jun 27 06:43:43 UTC 2024
 
[Container] 2024/06/27 06:43:43.993456 Running command flutter build web --profile --web-renderer html
Resolving dependencies...
Downloading packages...
_fe_analyzer_shared 70.0.0 (72.0.0 available)
_flutterfire_internals 1.3.35 (1.3.38 available)
> _macros 0.3.2 from sdk dart (was 0.3.0 from sdk dart)
analyzer 6.5.2 (6.7.0 available)
calendar_date_picker2 0.5.6 (1.1.5 available)
collection 1.18.0 (1.19.0 available)
device_info_plus 9.1.2 (10.1.0 available)
file_picker 6.2.1 (8.0.5 available)
firebase_auth 4.20.0 (5.1.1 available)
firebase_auth_platform_interface 7.3.0 (7.4.1 available)
firebase_auth_web 5.12.0 (5.12.3 available)
firebase_core 2.32.0 (3.1.1 available)
fl_chart 0.67.0 (0.68.0 available)
flutter_lints 2.0.3 (4.0.0 available)
http_parser 4.0.2 (4.1.0 available)
image_cropper 5.0.1 (7.0.5 available)
image_cropper_for_web 3.0.0 (5.0.4 available)
image_cropper_platform_interface 5.0.0 (6.0.3 available)
image_picker_android 0.8.12+1 (0.8.12+3 available)
internet_connection_checker_plus 2.4.2 (2.5.0 available)
js 0.6.7 (0.7.1 available)
lints 2.1.1 (4.0.0 available)
> macros 0.1.2-main.4 (was 0.1.2-main.0)
material_color_utilities 0.11.1 (0.12.0 available)
network_info_plus 4.1.0+1 (5.0.3 available)
network_info_plus_platform_interface 1.1.3 (2.0.0 available)
path_provider_android 2.2.4 (2.2.6 available)
pinput 4.0.0 (5.0.0 available)
rxdart 0.27.7 (0.28.0 available)
shared_preferences_android 2.2.2 (2.2.3 available)
shelf 1.4.1 (1.4.2 available)
syncfusion_flutter_core 24.2.9 (26.1.39 available)
syncfusion_flutter_datepicker 24.2.9 (26.1.39 available)
syncfusion_flutter_pdf 24.2.9 (26.1.39 available)
syncfusion_flutter_pdfviewer 24.2.8 (26.1.39 available)
syncfusion_flutter_signaturepad 24.2.9 (26.1.39 available)
syncfusion_pdfviewer_macos 24.2.9 (26.1.39 available)
syncfusion_pdfviewer_platform_interface 24.2.9 (26.1.39 available)
syncfusion_pdfviewer_web 24.2.8 (26.1.39 available)
syncfusion_pdfviewer_windows 24.2.9 (26.1.39 available)
url_launcher_android 6.3.2 (6.3.3 available)
> vm_service 14.2.4 (was 14.2.3)
Changed 3 dependencies!
39 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
 
Compiling lib/main.dart for the Web...
Warning: In index.html:37: Local variable for "serviceWorkerVersion" is deprecated. Use "{{flutter_service_worker_version}}" template token instead.
Warning: In index.html:46: "FlutterLoader.loadEntrypoint" is deprecated. Use "FlutterLoader.load" instead.
Target dart2js failed: ProcessException: Process exited abnormally with exit code 1:
/root/.pub-cache/hosted/pub.dev/image_cropper_platform_interface-5.0.0/lib/src/models/cropped_file/html.dart:32:38:
Error: The method 'UnmodifiableUint8ListView' isn't defined for the class 'CroppedFile'.
- 'CroppedFile' is from 'package:image_cropper_platform_interface/src/models/cropped_file/html.dart' ('/root/.pub-cache/hosted/pub.dev/image_cropper_platform_interface-5.0.0/lib/src/models/cropped_file/html.dart').
return Future<Uint8List>.value(UnmodifiableUint8ListView(_initBytes!));
^^^^^^^^^^^^^^^^^^^^^^^^^
Error: Compilation failed.
Command: /codebuild/output/src1485100722/src/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /codebuild/output/src1485100722/src/flutter/bin/cache/dart-sdk/bin/snapshots/dart2js.dart.snapshot --platform-binaries=/codebuild/output/src1485100722/src/flutter/bin/cache/flutter_web_sdk/kernel --invoker=flutter_tool -Ddart.vm.profile=true -DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/a9194f0f01f42175eaf82a8132167d9c54b60263/ -DFLUTTER_WEB_AUTO_DETECT=false -DFLUTTER_WEB_USE_SKIA=false --native-null-assertions --no-source-maps -o /codebuild/output/src1485100722/src/.dart_tool/flutter_build/0f5c8d84bd9c243a2d65e9e4b797d6c3/app.dill --packages=.dart_tool/package_config.json --cfe-only /codebuild/output/src1485100722/src/.dart_tool/flutter_build/0f5c8d84bd9c243a2d65e9e4b797d6c3/main.dart
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:122:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:318:19)
<asynchronous suspension>
#2      Dart2JSTarget.build (package:flutter_tools/src/build_system/targets/web.dart:193:5)
<asynchronous suspension>
#3      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:875:9)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:534:21)
<asynchronous suspension>
#5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:813:32)
<asynchronous suspension>
#6      Future.wait.<anonymous closure> (dart:async/future.dart:534:21)
<asynchronous suspension>
#7      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:813:32)
<asynchronous suspension>
#8      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:635:16)
<asynchronous suspension>
#9      WebBuilder.buildWeb (package:flutter_tools/src/web/compile.dart:92:34)
<asynchronous suspension>
#10     BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:229:5)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1403:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
<asynchronous suspension>
#17     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#19     main (package:flutter_tools/executable.dart:93:3)
<asynchronous suspension>
 
Compiling lib/main.dart for the Web...                             45.5s
Error: Failed to compile application for the Web.
 
[Container] 2024/06/27 06:45:15.244498 Command did not exit successfully flutter build web --profile --web-renderer html exit status 1
[Container] 2024/06/27 06:45:15.256156 Phase complete: BUILD State: FAILED
[Container] 2024/06/27 06:45:15.256176 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: flutter build web --profile --web-renderer html. Reason: exit status 1
[Container] 2024/06/27 06:45:15.289363 Entering phase POST_BUILD
[Container] 2024/06/27 06:45:15.289973 Running command
 
[Container] 2024/06/27 06:45:15.295512 Phase complete: POST_BUILD State: SUCCEEDED
[Container] 2024/06/27 06:45:15.295535 Phase context status code:  Message:
[Container] 2024/06/27 06:45:15.380964 Expanding base directory path: build/web/
[Container] 2024/06/27 06:45:15.383035 Assembling file list
[Container] 2024/06/27 06:45:15.383057 Expanding build/web/
[Container] 2024/06/27 06:45:15.384863 Expanding file paths for base directory build/web/
[Container] 2024/06/27 06:45:15.384876 Assembling file list
[Container] 2024/06/27 06:45:15.384880 Expanding **/*
[Container] 2024/06/27 06:45:15.388685 Found 14 file(s)
[Container] 2024/06/27 06:45:15.943134 Set report auto-discover timeout to 5 seconds
[Container] 2024/06/27 06:45:15.944110 Expanding base directory path:  .
[Container] 2024/06/27 06:45:15.946040 Assembling file list
[Container] 2024/06/27 06:45:15.946054 Expanding .
[Container] 2024/06/27 06:45:15.947774 Expanding file paths for base directory .
[Container] 2024/06/27 06:45:15.947787 Assembling file list
[Container] 2024/06/27 06:45:15.947790 Expanding **/*
[Container] 2024/06/27 06:45:16.051219 Found 137 file(s)
[Container] 2024/06/27 06:45:16.051267 Report auto-discover file discovery took 0.108132 seconds
[Container] 2024/06/27 06:45:16.052648 Phase complete: UPLOAD_ARTIFACTS State: SUCCEEDED
[Container] 2024/06/27 06:45:16.052671 Phase context status code:  Message:

**Comment by Aslamabdulla** [comment]
Target dart2js failed: ProcessException: Process exited abnormally with exit code 1:
../../../../.pub-cache/hosted/pub.dev/image_cropper_platform_interface-6.0.3/lib/src/models/cropped_file/html.dart:32:38:
Error: The method 'UnmodifiableUint8ListView' isn't defined for the class 'CroppedFile'.
 - 'CroppedFile' is from 'package:image_cropper_platform_interface/src/models/cropped_file/html.dart'
 ('../../../../.pub-cache/hosted/pub.dev/image_cropper_platform_interface-6.0.3/lib/src/models/cropped_file/html.dart').
      return Future<Uint8List>.value(UnmodifiableUint8ListView(_initBytes));
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^
Error: Compilation failed.
  Command: /Users/azlam/Documents/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
  /Users/azlam/Documents/flutter/bin/cache/dart-sdk/bin/snapshots/dart2js.dart.snapshot
  --platform-binaries=/Users/azlam/Documents/flutter/bin/cache/flutter_web_sdk/kernel --invoker=flutter_tool
  -Ddart.vm.profile=true
  -DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/a9194f0f01f42175eaf82a8132167d9c54b60263/
  -DFLUTTER_WEB_AUTO_DETECT=false -DFLUTTER_WEB_USE_SKIA=false --native-null-assertions --no-source-maps -o
  /Users/azlam/Documents/Infotura/my_slip/my_slip/.dart_tool/flutter_build/0f5c8d84bd9c243a2d65e9e4b797d6c3/app.dill
  --packages=.dart_tool/package_config.json --cfe-only
  /Users/azlam/Documents/Infotura/my_slip/my_slip/.dart_tool/flutter_build/0f5c8d84bd9c243a2d65e9e4b797d6c3/main.dart
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:122:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:318:19)
<asynchronous suspension>
#2      Dart2JSTarget.build (package:flutter_tools/src/build_system/targets/web.dart:193:5)
<asynchronous suspension>
#3      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:875:9)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:534:21)
<asynchronous suspension>
#5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:813:32)
<asynchronous suspension>
#6      Future.wait.<anonymous closure> (dart:async/future.dart:534:21)
<asynchronous suspension>
#7      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:813:32)
<asynchronous suspension>
#8      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:635:16)
<asynchronous suspension>
#9      WebBuilder.buildWeb (package:flutter_tools/src/web/compile.dart:92:34)
<asynchronous suspension>
#10     BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:229:5)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1403:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
<asynchronous suspension>
#17     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#19     main (package:flutter_tools/executable.dart:93:3)
<asynchronous suspension>

Compiling lib/main.dart for the Web...                             74.9s
Error: Failed to compile application for the Web.
azlam@apples-MacBook-Pro my_slip % 



Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.23.0-13.0.pre.357, on macOS 13.6.7 22G720 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google
    Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.90.2)

**Comment by hnvn** [comment]
fixed in v7.1.0
