### ISSUE TITLE
ImageCropperDelegate.java uses or overrides a deprecated API.

### ISSUE THREAD

**Issue by erkinovalim** [hnvn/flutter_image_cropper#520]
Note: /Users/alim/.pub-cache/hosted/pub.dev/image_cropper-7.1.0/android/src/main/java/vn/hunghd/flutter/plugins/imagecropper/ImageCropperDelegate.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by ZhiaDev** [comment]
i have the same warning too 😑

**Comment by hnvn** [comment]
fixed in v8.0.2
