### ISSUE TITLE
AndroidUiSettings Appbar no SafeArea

### ISSUE THREAD

**Issue by 944095635** [hnvn/flutter_image_cropper#539]
![Screenshot_2024-12-16-11-03-11-126_xyz xycrypto j](https://github.com/user-attachments/assets/50955c82-63dd-498b-a1b0-19948a88122d)

this appbar in the status bar.

**Comment by 944095635** [comment]
flutter_windows_3.27.0-stable  this error
3.26 did not encounter this issue

**Comment by mikejones3** [comment]
I am having this issue as well

**Comment by hnvn** [comment]
I've released new version to workaround this issue: https://pub.dev/packages/image_cropper/changelog

**Comment by sydneyagcaoili** [comment]
This happened to me again just now with Samsung Galaxy S24 Ultra

**Comment by alistair-riskmemo** [comment]
I've just had a customer support ticket raised with this issue
