### ISSUE TITLE
Android dependency 'com.github.yalantis:ucrop' has different version

### ISSUE THREAD

**Issue by kmvignesh** [hnvn/flutter_image_cropper#54]
After adding the dependency and activity tag in AndroidManifest.xml file getting following error.

Android dependency 'com.github.yalantis:ucrop' has different version for the compile (2.2.2-native) and runtime (2.2.3) classpath. You should manually set the same version via DependencyResolution

**Comment by hnvn** [comment]
This plugin doesn't use 'com.github.yalantis:ucrop' 2.2.2-native. Can you check your Android project setting?
