### ISSUE TITLE
AAPT: error: style attribute 'android:attr/windowOptOutEdgeToEdgeEnforcement' not found.

### ISSUE THREAD

**Issue by kjw3676** [hnvn/flutter_image_cropper#543]
I updated version 8.1.0.

I can not build it. I tried android sdk flutter SdkVersion and 35.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     ERROR: ___/build/app/intermediates/incremental/debug/mergeDebugResources/merged.dir/values-v35/values-v35.xml:4: AAPT: error: style attribute 'android:attr/windowOptOutEdgeToEdgeEnforcement' not found.

What could be the fault?

**Comment by MayurChavda123456** [comment]
How Didi you Solved This

**Comment by ilovexy2tom** [comment]
我也遇到了这个问题

**Comment by MayurChavda123456** [comment]
then why did you deleted this issue i thought you got any way to solve it

**Comment by pndychrg** [comment]
Anyone know how to solve this issue

**Comment by kjw3676** [comment]
So sorry to late.

The theme in manifest has changed as the Android library has been versioned up.

before: android:theme="@style/Theme.AppCompat.Light.NoActionBar"

now: android:theme="@style/Ucrop.CropTheme"

**Comment by pndychrg** [comment]
Okay I did that and it's running in debug mode, but It's giving me same error when I'm trying to build the apk 
Also Is the Android SDK Version is required to be 35 for it ?

**Comment by kjw3676** [comment]
I'm not sure, but I think it would be better to use the sdk 35.
