### ISSUE TITLE
Are there any plans to add support for other platforms, such as macOS, Windows, or Linux?

### ISSUE THREAD

**Issue by stoneLee81** [hnvn/flutter_image_cropper#545]

**Comment by hnvn** [comment]
currently don't have plans to address these targets as they fall outside my expertise; I specialize in mobile and web development. However, this plugin is designed as a [Flutter Federated Plugin](https://docs.flutter.dev/packages-and-plugins/developing-packages), making it possible for developers with experience in other platforms (e.g., macOS, Windows) to contribute and extend its functionality to those platforms.
