### ISSUE TITLE
Android Resource Linking Failed: Attribute 'windowOptOutEdgeToEdgeEnforcement' Not Found

### ISSUE THREAD

**Issue by istiaksaif** [hnvn/flutter_image_cropper#548]
I encountered an issue while integrating the image_cropper library into my Android project. The build fails during the :app:processDebugResources task with the following error:

`Execution failed for task ':app:processDebugResources'.  

> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction  
   > Android resource linking failed  

     com.ai.language.learning.app-mergeDebugResources-72:/values-v35/values-v35.xml:4: error: style attribute 'android:attr/windowOptOutEdgeToEdgeEnforcement' not found.  

     error: failed linking references.
`

This issue seems to be related to the values-v35.xml file

**Comment by JayMoliya33** [comment]
++

**Comment by ib-ganz** [comment]
same here

**Comment by Fahmy07** [comment]
Same here.

**Comment by mthuong** [comment]
Solution at https://github.com/hnvn/flutter_image_cropper/issues/547
