### ISSUE TITLE
App crashes when opening cropper in example

### ISSUE THREAD

**Issue by VictorUvarov** [hnvn/flutter_image_cropper#57]
## flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale en-US)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.35.1)
[✓] Connected device (1 available)

• No issues found!

## Package version
image_cropper: ^1.0.2

## Debug output
Launching lib/main.dart on Pixel 2 XL in debug mode...
Built build/app/outputs/apk/debug/app-debug.apk.
I/com.example.ap(30041): Rejecting re-init on previously-failed class java.lang.Class<com.yalantis.ucrop.UCropFragment>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/app/Fragment;
I/com.example.ap(30041):   at com.yalantis.ucrop.UCrop com.yalantis.ucrop.UCrop.of(android.net.Uri, android.net.Uri) (UCrop.java:64)
I/com.example.ap(30041):   at void vn.hunghd.flutter.plugins.imagecropper.ImageCropperDelegate.startCrop(io.flutter.plugin.common.MethodCall, io.flutter.plugin.common.MethodChannel$Result) (ImageCropperDelegate.java:84)
I/com.example.ap(30041):   at void vn.hunghd.flutter.plugins.imagecropper.ImageCropperPlugin.onMethodCall(io.flutter.plugin.common.MethodCall, io.flutter.plugin.common.MethodChannel$Result) (ImageCropperPlugin.java:42)
I/com.example.ap(30041):   at void io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(java.nio.ByteBuffer, io.flutter.plugin.common.BinaryMessenger$BinaryReply) (MethodChannel.java:201)
I/com.example.ap(30041):   at void io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(java.lang.String, byte[], int) (DartMessenger.java:88)
I/com.example.ap(30041):   at void io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(java.lang.String, byte[], int) (FlutterJNI.java:219)
I/com.example.ap(30041):   at void android.os.MessageQueue.nativePollOnce(long, int) (MessageQueue.java:-2)
I/com.example.ap(30041):   at android.os.Message android.os.MessageQueue.next() (MessageQueue.java:326)
I/com.example.ap(30041):   at void android.os.Looper.loop() (Looper.java:160)
I/com.example.ap(30041):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6718)
I/com.example.ap(30041):   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/com.example.ap(30041):   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:493)
I/com.example.ap(30041):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:858)
I/com.example.ap(30041): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.app.Fragment" on path: DexPathList[[zip file "/data/app/com.example.app--2mY6e9epGMEJ0lkKLX2fg==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.app--2mY6e9epGMEJ0lkKLX2fg==/lib/arm64, /data/app/com.example.app--2mY6e9epGMEJ0lkKLX2fg==/base.apk!/lib/arm64-v8a, /system/lib64]]
I/com.example.ap(30041):   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:134)
I/com.example.ap(30041):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
I/com.example.ap(30041):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/com.example.ap(30041):   at com.yalantis.ucrop.UCrop com.yalantis.ucrop.UCrop.of(android.net.Uri, android.net.Uri) (UCrop.java:64)
I/com.example.ap(30041):   at void vn.hunghd.flutter.plugins.imagecropper.ImageCropperDelegate.startCrop(io.flutter.plugin.common.MethodCall, io.flutter.plugin.common.MethodChannel$Result) (ImageCropperDelegate.java:84)
I/com.example.ap(30041):   at void vn.hunghd.flutter.plugins.imagecropper.ImageCropperPlugin.onMethodCall(io.flutter.plugin.common.MethodCall, io.flutter.plugin.common.MethodChannel$Result) (ImageCropperPlugin.java:42)
I/com.example.ap(30041):   at void io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(java.nio.ByteBuffer, io.flutter.plugin.common.BinaryMessenger$BinaryReply) (MethodChannel.java:201)
I/com.example.ap(30041):   at void io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(java.lang.String, byte[], int) (DartMessenger.java:88)
I/com.example.ap(30041):   at void io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(java.lang.String, byte[], int) (FlutterJNI.java:219)
I/com.example.ap(30041):   at void android.os.MessageQueue.nativePollOnce(long, int) (MessageQueue.java:-2)
I/com.example.ap(30041):   at android.os.Message android.os.MessageQueue.next() (MessageQueue.java:326)
I/com.example.ap(30041):   at void android.os.Looper.loop() (Looper.java:160)
I/com.example.ap(30041):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6718)
I/com.example.ap(30041):   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/com.example.ap(30041):   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:493)
I/com.example.ap(30041):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:858)
...

**Comment by hnvn** [comment]
Can you run the example project?

**Comment by hnvn** [comment]
The example project works well in my machine. Do you change any project configuration?

**Comment by VictorUvarov** [comment]
It works fine now. I just didn't seem to have the right settings in android manifest.xml file
