### ISSUE TITLE
is it possible to add freetransform crop rectangle ?

### ISSUE THREAD

**Issue by Xgamefactory** [hnvn/flutter_image_cropper#58]
there is excellent open source Adobe Air plugin for android and IOS
https://github.com/freshplanet/ANE-ImagePicker

it supports user to be able drag and define crop rectangle.

**Comment by hnvn** [comment]
I would like to keep this plugin simple and light. I don't have a plan to integrate more third libraries into this project.

**Comment by Xgamefactory** [comment]
it it not extra feature currently on android there is fixed rectangle for crop i asked just to make it freen transform user drag defined that is all.
