### ISSUE TITLE
Double tap on done button crashes the iOS app

### ISSUE THREAD

**Issue by vlada3003** [hnvn/flutter_image_cropper#60]
1. Open the example app
2. Choose an image
3. Click on the crop fab.
4. Choose section of the image for cropping.
5. Click done button twice and app will crash. Thread 1: EXC_BAD_ACCESS (code=1, address=0x10).

As far as I can figure out _result is nil in ImageCropperPlugin.m. 

Crash is found here:

if ([[NSFileManager defaultManager] createFileAtPath:tmpPath contents:data attributes:nil]) {
        _result(tmpPath); <----- CRASH Thread 1: EXC_BAD_ACCESS
    } else {
        _result([FlutterError errorWithCode:@"create_error"
                                    message:@"Temporary file could not be created"
                                    details:nil]);
    }

Wrapping _result with nil check or removing setting _result to nil from this class will prevent the crash. However, I'm not sure if this is the right thing to do since I'm not sure why setting _result to nil was done in the first place, nor will it show some other problems within the library.

**Comment by Sevencats** [comment]
I have the same question.please help me!! thank you!!!

**Comment by saprahits** [comment]
Very disappoint this point i have create 16+ app getting same as all app issue. 
please upload latest version.
