### ISSUE TITLE
Why does the % not start with 100%?

### ISSUE THREAD

**Issue by momoDragon** [hnvn/flutter_image_cropper#63]
![Screenshot_90](https://user-images.githubusercontent.com/40727575/60956517-92066e80-a335-11e9-956b-280348b3291e.png)

Why is it 299% instead of 100%?

**Comment by bhurlbert** [comment]
Image_Cropper has potential! However, this behaviour is a blocker for me; my testing results in that the image cannot be rotated without inheriting the size constraints of the zoom window. Furthermore, if a crop is needed it's impossible to trim 50 pixels on all side of the image for instance.

I'm not sure who's keeping up with images on GitHub, but my devices don't match the screen shots.
