### ISSUE TITLE
It would be perfect if you could hide the bottom toolbar

### ISSUE THREAD

**Issue by Menusyes** [hnvn/flutter_image_cropper#67]
For me, not being able to customize is a very serious problem, which will cause me to not be able to continue using it, but, I will continue to look forward to future releases

**Comment by iot-mcy** [comment]
uCrop 原本可以隐藏底部工具栏的，建议把这个方法开放出来

**Comment by hnvn** [comment]
Try new v1.1.0 for better UI customization.
