### ISSUE TITLE
Can you support custom clipped cancel and done text? I need to support Chinese

### ISSUE THREAD

**Issue by dmskys** [hnvn/flutter_image_cropper#69]
Can you support custom clipped cancel and done text? I need to support Chinese

**Comment by hnvn** [comment]
Have a look at #37

**Comment by dmskys** [comment]
我找不到cancel text 和 done text 我只知道了这些？请问cancel text 和 done text 如何替换？

<string name="ucrop_label_original">Original</string>
<string name="ucrop_label_edit_photo">Edit Photo</string>
<string name="ucrop_menu_next">Next</string>
<string name="ucrop_rotate">Rotate</string>
<string name="ucrop_scale">Scale</string>
<string name="ucrop_crop">Crop</string>

**Comment by hnvn** [comment]
As I as remember, there's no "cancel" and "done" text in our cropping UI, it's represented as icons

**Comment by dmskys** [comment]
Sorry, I'm using iPhone debugging. I found that Android and IOS display different shear interfaces. IOS shear interface will have cancel text and done text.

**Comment by hnvn** [comment]
Yep, this plugin is based on different native libraries in 2 platforms.

**Comment by dsmjoy** [comment]
@dmskys  have you resolve it?
