### ISSUE TITLE
Feature request: Add a localization parameter for "rotate" and "scale" buttons

### ISSUE THREAD

**Issue by Igor3T** [hnvn/flutter_image_cropper#71]
Could you kindly add parameters for "rotate" and "scale" button's titles localizations? 

There should be something like:
await ImageCropper.cropImage(
        sourcePath: image.path,
        ...
        rotateButtonTitle : "Поворот",
        scaleButtonTitle : "Размер"
        ....
    );

That would be really great! Thank you for your awesome cropper!

**Comment by hnvn** [comment]
Have a look at #37

**Comment by Igor3T** [comment]
The link helped me a lot. Thank you!

пн, 19 авг. 2019 г. в 19:35, HungHD <notifications@github.com>:

**Comment by Leptopoda** [comment]
Hi there,
is there a way to also localize the ios part? Haven't found anything in the libs repo.
