### ISSUE TITLE
error：java.lang.NoClassDefFoundError: Failed resolution of: Lcom/yalantis/ucrop/UCropActivity;

### ISSUE THREAD

**Issue by Ian0903** [hnvn/flutter_image_cropper#72]
E/flutter (16700): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(40)] java.lang.NoClassDefFoundError: Failed resolution of: Lcom/yalantis/ucrop/UCropActivity;
E/flutter (16700): 	at com.yalantis.ucrop.UCrop.getIntent(UCrop.java:186)
E/flutter (16700): 	at com.yalantis.ucrop.UCrop.start(UCrop.java:138)
E/flutter (16700): 	at com.yalantis.ucrop.UCrop.start(UCrop.java:128)
E/flutter (16700): 	at vn.hunghd.flutter.plugins.imagecropper.ImageCropperDelegate.startCrop(ImageCropperDelegate.java:91)
E/flutter (16700): 	at vn.hunghd.flutter.plugins.imagecropper.ImageCropperPlugin.onMethodCall(ImageCropperPlugin.java:42)
E/flutter (16700): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/flutter (16700): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/flutter (16700): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:643)
E/flutter (16700): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (16700): 	at android.os.MessageQueue.next(MessageQueue.java:148)
E/flutter (16700): 	at android.os.Looper.loop(Looper.java:151)
E/flutter (16700): 	at android.app.ActivityThread.main(ActivityThread.java:5898)
E/flutter (16700): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (16700): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/flutter (16700): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1019)
E/flutter (16700): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:814)
E/flutter (16700): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.yalantis.ucrop.UCropActivity" on path: DexPathList[[zip file "/data/app/com.example.smart_talk-2/base.apk"],nativeLibraryDirectories=[/data/app/com.example.smart_talk-2/lib/arm64, /vendor/lib64, /system/lib64]]
E/flutter (16700): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/flutter (16700): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
E/flutter (16700): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
E/flutter (16700): 	... 16 more
E/flutter (16700): 	Suppressed: java.lang.NoClassDefFoundError: com.yalantis.ucrop.UCropActivity
E/flutter (16700): 		at dalvik.system.DexFile.defineClassNative(Native Method)
E/flutter (16700): 		at dalvik.system.DexFile.defineClass(DexFile.java:226)
E/flutter (16700): 		at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
E/flutter (16700): 		at dalvik.system.DexPathList.findClass(DexPathList.java:322)
E/flutter (16700): 		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
E/flutter (16700): 		... 18 more
E/flutter (16700): 	Suppressed: java.lang.ClassNotFoundException: com.yalantis.ucrop.UCropActivity
E/flutter (16700): 		at java.lang.Class.classForName(Native Method)
E/flutter (16700): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
E/flutter (16700): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
E/flutter (16700): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
E/flutter (16700): 		... 17 more
E/flutter (16700): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
E/flutter (16700): 
F/flutter (16700): [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(77)] Check failed: CheckException(env). 
F/libc    (16700): Fatal signal 6 (SIGABRT), code -6 in tid 16700 (mple.smart_talk)
Lost connection to device.

**Comment by topnax** [comment]
Having the same issue.

**Comment by ghanyin** [comment]
you can try in gradle.properties  file  , add：
android.enableJetifier=true
android.useAndroidX=true

**Comment by hnvn** [comment]
Looks like a AndroidX migration problem. Have you tried the example project yet?
