### ISSUE TITLE
Feature request: keep the Exif tags

### ISSUE THREAD

**Issue by felpsio** [hnvn/flutter_image_cropper#74]
Thanks for the awesome package.

I need to crop the image according to the user preferences but I need to keep the original Exif files. Would be nice to add an option in the package the preserve the Exif tags after cropping.

**Comment by hnvn** [comment]
What platform do you mention about? And Would you care to create a pull request for it? 

In my view, this feature would be requested on native library repositories which this plugin is based on ([uCrop](https://github.com/Yalantis/uCrop) and [TOCropViewController](https://github.com/TimOliver/TOCropViewController)). The plugin only uses platform channel to communicate with those libraries. It's hard to implement this feature without supports from those libraries.

**Comment by felpsio** [comment]
iOS and Android. Good idea, I will create a PR on the respective GitHubs. Thanks for the suggestion :)

**Comment by felpsio** [comment]
I just created a PR on TOCropViewController.

I noticed that the uCrop already allows it. In its documentation is written:

> Version: 2.0
Native image crop (able to crop high-resolution images, e.g. 16MP & 32MP images on Nexus 5X).
WebP compression format is not supported at the moment (choose JPEG or PNG).
**Now library copies EXIF data to cropped image (size and orientation are updated).**

**Comment by hnvn** [comment]
As soon as it is merged, you can update our plugin.

**Comment by felpsio** [comment]
the `ToCropViewController` won't add this in the library.

So I guess that users from this package that needs the exif should extract the info before sending to the package and then find a way to merge it.

Thanks for your time checking the request.

```
import 'package:exif/exif.dart';

Map<String, IfdTag> tags = readExifFromBytes( File(img.path) );

File croppedFile = await ImageCropper.cropImage(sourcePath: img.path);
```
