### ISSUE TITLE
no ui customization for ios (ok android)

### ISSUE THREAD

**Issue by juliengit2** [hnvn/flutter_image_cropper#79]
I upgraded to the latest version and there is no method to customize UI on ios, there are present only for android, pity

where are toolbarColor and   toolbarWidgetColor   for ios ?

**Comment by hnvn** [comment]
Have you looked at `IOSUiSettings` yet? And the plugin can only provide the UI customization on properties that the native libraries support, `TOCropViewController` in case of iOS.

**Comment by juliengit2** [comment]
Hi, yes I looked both in` IOSUiSettings` and in your plugin project sample, and there are no are toolbarColor or toolbarWidgetColor available (ok only for android, with great example in your plugin project).

Is it possible to customize on ios ? 'cause it's written in the doc but I cannot figure out how to do that

Thank you

**Comment by hnvn** [comment]
Here are the source codes of the entry point class of `TOCropViewcontroller`, it exposes all properties that can be used to customize UI:
https://github.com/TimOliver/TOCropViewController/blob/master/Objective-C/TOCropViewController/TOCropViewController.h

**Comment by fralways** [comment]
text customization is really needed. could you add support for it? @hnvn [https://github.com/TimOliver/TOCropViewController/issues/202](url)

**Comment by jpsjanuario** [comment]
Any updates about text customization on iOS?
