### ISSUE TITLE
Can crop the image with Dart?

### ISSUE THREAD

**Issue by koudle** [hnvn/flutter_image_cropper#8]
Does Dart have ways to process images?

**Comment by hnvn** [comment]
Crop in code or present an UI to let user crop an image?

**Comment by koudle** [comment]
You use the native code to crop the image,I mean can you use the dart code to crop the image? I didn't find ways to crop the image with Dart code.

**Comment by hnvn** [comment]
Try using BoxDecoration with a DecorationImage. This plugin aims to provide an interface to let users manipulate with images on purposes of cropping and rotating. Of course, we can accomplish those features in pure Dart but I don't think it can give better performance than native codes do.

**Comment by hnvn** [comment]
English, please
