### ISSUE TITLE
Custom CropAspectRatioPreset

### ISSUE THREAD

**Issue by Emmarex** [hnvn/flutter_image_cropper#81]
Can you add support for ``CropAspectRatioPreset`` or use of ``CropAspectRatioPreset`` and ``aspectRatio`` ?

**Comment by hnvn** [comment]
What the feature do you want to customize? Is it the list of crop aspect ratio in menu view? If it is, it is only supported in Android native library, in iOS, there's only a list of preset values.

**Comment by Emmarex** [comment]
Would like to add custom aspect ratio presets. Something like this 

``
aspectRatioPresets: [
    CropAspectRatioPreset.square,
    CropAspectRatioPreset.ratio4x3,
    CropAspectRatioPreset.ratio5x3,
    CropAspectRatioPreset(ratioX: 3, ratioY: 4),
    CropAspectRatioPreset(ratioX: 3, ratioY: 5)
]
``

**Comment by hnvn** [comment]
This feature has not been supported in iOS yet
https://github.com/TimOliver/TOCropViewController/blob/master/Objective-C/TOCropViewController/Constants/TOCropViewConstants.h#L37

**Comment by jithinvarghese** [comment]
Is there any solution for the above issue in 2021?

**Comment by alexislg2** [comment]
Yes, that would be amazing
