### ISSUE TITLE
crashing in the android app

### ISSUE THREAD

**Issue by dhruvil2000** [hnvn/flutter_image_cropper#82]
Hello friend, I know this plugin is super cool in flutter community,
But since I upgraded the image_cropper plugin, it is crashing the application.
Please solve the issue.

**Comment by hnvn** [comment]
Can you give me some logs?

**Comment by Sylvain17** [comment]
Rejecting re-init on previously-failed class java.lang.Class<androidx.appcompat.widget.AppCompatTextView>: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/core/widget/TintableCompoundDrawablesView;

**Comment by hnvn** [comment]
I believe it's same as #78

**Comment by Sylvain17** [comment]
Yes, same bug and same solution is working.

I needed to comment :
```
subprojects {
        project.configurations.all {
            resolutionStrategy.eachDependency { details ->
                if (details.requested.group == 'androidx.core'
                        && !details.requested.name.contains('androidx') ) {
                    details.useVersion "1.0.1"
                }
            }
        }
    }
```

Thx

**Comment by dhruvil2000** [comment]
so what do you mean? add this lines or not in android gradle? @hnvn @Sylvain17 

`subprojects {
        project.configurations.all {
            resolutionStrategy.eachDependency { details ->
                if (details.requested.group == 'androidx.core'
                        && !details.requested.name.contains('androidx') ) {
                    details.useVersion "1.0.1"
                }
            }
        }
    }
`

**Comment by Sylvain17** [comment]
Lol, comment this lines (or remove them)

**Comment by momoDragon** [comment]
This solved my issue too. Thanks a million. and thanks @hnvn  for the plugin

**Comment by hnvn** [comment]
You guys, please look at existed issues before create a new one. Thanks

**Comment by momoDragon** [comment]
> You guys, please look at existed issues before create a new one. Thanks

My apologies
