### ISSUE TITLE
App crash similar to #78 but no solution

### ISSUE THREAD

**Issue by jasonlaw** [hnvn/flutter_image_cropper#86]
Hi @hnvn ,

I know this issue has been reported few times by others and solution given is to comment out the code like below:

```
subprojects {
        project.configurations.all {
            resolutionStrategy.eachDependency { details ->
                if (details.requested.group == 'androidx.core'
                        && !details.requested.name.contains('androidx') ) {
                    details.useVersion "1.0.1"
                }
            }
        }
    }
```
However, I have searched through my project but cannot locate the above code. Did I miss anything?

**Comment by coppolla** [comment]
same problem here

**Comment by jasonlaw** [comment]
Hi @coppolla ,

I have the issue fixed by applying the following code into the app build.gradle file:

configurations.all {
    resolutionStrategy {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'androidx.core') {
            details.useVersion "1.0.1"
            }
            if (details.requested.group == 'androidx.lifecycle') {
            details.useVersion "2.0.0"
            }
            if (details.requested.group == 'androidx.versionedparcelable') {
            details.useVersion "1.0.0"
            }
            if (details.requested.group == 'androidx.fragment') {
            details.useVersion "1.0.0"
            }
            if (details.requested.group == 'androidx.appcompat') {
            details.useVersion "1.0.1"
            }
        }
    }
}

Hope this help.

**Comment by amorenew** [comment]
I think it is related to https://github.com/hnvn/flutter_image_cropper/issues/113
In version 1.1.2 no crash
