### ISSUE TITLE
IOS not work aspectRatioLockEnabled

### ISSUE THREAD

**Issue by SunryTeang** [hnvn/flutter_image_cropper#90]
when i apply
 aspectRatio: CropAspectRatio(ratioX: 1,ratioY: 1)
so 
aspectRatioLockEnabled
not work

**Comment by hnvn** [comment]
As document said:
> **aspectRatio**: controls the aspect ratio of crop bounds. If this values is set, the cropper is locked and user can't change the aspect ratio of crop bounds.
It means that **aspectRatio** will override the behavior of **aspectRatioLockEnabled**
