### ISSUE TITLE
Need a Image cropping option like circular, rectangular and rectangular with some corner radius.

### ISSUE THREAD

**Issue by jazzbpn** [hnvn/flutter_image_cropper#91]
Hello dev, This is a useful plugin. It would be more awesome if you add the cropping options like:
1. Circular Image
2. Rectangular Image
3. Rectangular with some corner radius.

Thanks for the good plugin. Will be waiting for your reply.

**Comment by hnvn** [comment]
It's beyond the capability of this repository, you should request this feature in two native library repositories [uCrop](https://github.com/Yalantis/uCrop) and [TOCropViewController](https://github.com/TimOliver/TOCropViewController). Until both native libraries support it, I can do nothing to bring this feature on Flutter. Thanks for your feedback.
