### ISSUE TITLE
Cannot build and run on iOS with latest updates

### ISSUE THREAD

**Issue by davbaron** [hnvn/flutter_image_cropper#94]
I recently updated both Flutter and flutter_image_cropper to latest versions. Upon trying to debug/run on iPhone simulator I get stopped.  The only 'errors' that I can recognize are as follows:

[!] CocoaPods could not find compatible versions for pod "TOCropViewController":
      In snapshot (Podfile.lock):
        TOCropViewController (= 2.5.0, ~> 2.5.0)

      In Podfile:
        image_cropper (from `.symlinks/plugins/image_cropper/ios`) was resolved to 0.0.1, which depends on
          TOCropViewController (~> 2.5.1)

    Specs satisfying the `TOCropViewController (= 2.5.0, ~> 2.5.0), TOCropViewController (~> 2.5.1)` dependency were found, but they required a higher minimum deployment target.

The debugger ends with:
Error running pod install
Error launching application on iPhone X

I opened the Podfile.lock file and there is an entry with the following:
- image_cropper (0.0.1):
    - Flutter
    - TOCropViewController (~> 2.5.0)
  
Is this something I can/should just change, or can you advise differently?

Thank you,

-David

**Comment by RafaRuiz** [comment]
Despite the other answers, no "update" worked for me.
Instead I deleted the Podfile.lock and run `pod install` again.
Worked.
